import {useState} from 'react';
import {RefreshCw} from 'lucide-react';
import {Button,EmptyState} from '../../components/ui';
import {useI18n} from '../../i18n';
import {Pager,ResourceState,useResource} from '../platform/common';
import {settingsCopy,type SettingsCopy} from './settings.copy';
import type {Account} from './AccountsPanel';
type AuditEntry={id:string;actor:string|null;action:string;entity:string;entityId:string|null;details:Record<string,unknown>;requestId:string|null;createdAt:string};
function valueText(value:unknown,c:SettingsCopy):string{if(value===null||value===undefined)return '—';if(typeof value==='boolean')return value?c.yes:c.no;if(Array.isArray(value))return value.map(item=>valueText(item,c)).join(', ');if(typeof value==='object')return Object.entries(value).map(([key,item])=>`${key}: ${valueText(item,c)}`).join('; ');return String(value);}
export function AuditPanel(){const {locale}=useI18n();const c=settingsCopy(locale);const [page,setPage]=useState(1);const [draft,setDraft]=useState('');const [filter,setFilter]=useState('');const params=new URLSearchParams({page:String(page),limit:'30',...(filter?{action:filter}:{})});const resource=useResource<AuditEntry[]>(`/admin/audit?${params}`);const accounts=useResource<Account[]>('/admin/accounts');const detailLabels:Record<string,string>={login:c.login,role:c.role,employeeId:c.profile,active:c.active,passwordChanged:c.passwordChanged,issuer:c.issuer};return <><form className="settings-toolbar" onSubmit={e=>{e.preventDefault();setFilter(draft.trim());setPage(1);}}><label className="settings-filter">{c.actionFilter}<input value={draft} maxLength={100} onChange={e=>setDraft(e.target.value)} list="settings-audit-actions"/><datalist id="settings-audit-actions">{['account.create','account.update','oidc.link','guide.publish','guide.archive','guide.contact_update','guide.contact_create','translation.approve'].map(action=><option key={action} value={action}/>)}</datalist></label><Button type="submit">{c.apply}</Button><Button variant="secondary" onClick={()=>{setDraft('');setFilter('');setPage(1);}}>{c.clear}</Button><Button variant="ghost" aria-label={c.refresh} disabled={resource.loading} onClick={resource.reload}><RefreshCw size={17}/></Button></form><ResourceState loading={resource.loading} error={resource.error} retry={resource.reload}>{resource.data?.length?<div className="settings-audit-list">{resource.data.map(entry=><article key={entry.id} className="card"><div className="settings-audit-heading"><strong>{entry.action}</strong><time dateTime={entry.createdAt}>{new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(entry.createdAt))}</time></div><dl className="settings-review"><div><dt>{c.actor}</dt><dd>{accounts.data?.find(account=>account.id===entry.actor)?.displayName??entry.actor??c.system}</dd></div><div><dt>{c.entity}</dt><dd>{entry.entity}{entry.entityId?` · ${entry.entityId}`:''}</dd></div></dl>{(Object.keys(entry.details??{}).length>0||entry.requestId)&&<details><summary>{c.details}</summary><dl className="settings-review">{Object.entries(entry.details??{}).map(([key,value])=><div key={key}><dt>{detailLabels[key]??key}</dt><dd>{valueText(value,c)}</dd></div>)}{entry.requestId&&<div><dt>{c.requestId}</dt><dd>{entry.requestId}</dd></div>}</dl></details>}</article>)}</div>:<EmptyState title={c.emptyAudit}/>}<Pager page={resource.meta?.page??page} total={resource.meta?.total??0} limit={30} onChange={setPage}/></ResourceState></>;}
