import { useEffect, useRef, useState, type FormEvent } from 'react';
import type { ImportResult, Session } from '../../api';
import { Badge, Button, EmptyState, ErrorState, Loading } from '../../components/ui';
import { Modal, Pager, ResourceState, useAction, useResource } from '../platform/common';
import { useIntegrationCopy, type IntegrationCopyKey } from './integrations.copy';
import './integrations.css';

type Config = { configuredTargets:string[]; ssoConfigured:boolean; webhooksEnabled:boolean; messengerTargetKey:string|null; aiProvider:'openai'|'self_hosted'; aiEnabled:boolean };
type Webhook = { id:string; name:string; targetKey:string; topics:string[]; active:boolean };
type Delivery = { id:string; subscriptionId:string; eventId:string; status:string; attempts:number; nextAttemptAt:string|null };
type Identity = { providerKey:string; entityType:'employee'|'event'; externalId:string; localId:string };
type Lookup = { id?:string; name?:string; eventId?:string; title?:string; department?:string };
type ImportData = { history?:Record<string,unknown>[]; employees?:Record<string,unknown> };
type ImportPayload = ImportData & {providerKey:string;messageId:string};
const topics = {'goal.changed':'goalChanged','participation.completed':'completed','event.published':'published','notification.created':'notification'} as const;
function deliveryTime(value:string|null,locale:string) {
 if(!value)return '—';const date=new Date(value);return Number.isNaN(date.getTime())?'—':new Intl.DateTimeFormat(locale==='kk'?'kk-KZ':locale==='ru'?'ru-RU':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(date);
}

export function IntegrationsPanel({session}:{session:Session}) {
 const {c}=useIntegrationCopy();const [section,setSection]=useState<'status'|'webhooks'|'identities'|'imports'>('status');
 const config=useResource<Config>(session.user.role==='admin'?'/integrations':null);
 if(session.user.role!=='admin')return <EmptyState title={c('adminOnly')}/>;
 return <div className="integrations-panel"><nav className="integrations-nav" aria-label={c('title')}>{(['status','webhooks','identities','imports'] as const).map(item=><button key={item} type="button" aria-pressed={section===item} onClick={()=>setSection(item)}>{c(item)}</button>)}</nav>
 {section==='status'&&<section className="platform-card integrations-card"><div className="integrations-heading"><h2>{c('status')}</h2><Button size="small" variant="ghost" onClick={config.reload}>{c('refresh')}</Button></div><p>{c('serverOnly')}</p><ResourceState loading={config.loading} error={config.error} retry={config.reload}>{config.data&&<><h3>{c('targets')}</h3>{config.data.configuredTargets.length?<ul className="integrations-target-list">{config.data.configuredTargets.map(key=><li key={key}>{key}</li>)}</ul>:<p className="platform-notice">{c('noTargets')}</p>}<dl className="platform-value-list"><div><dt>{c('worker')}</dt><dd>{c(config.data.webhooksEnabled?'on':'off')}</dd></div><div><dt>{c('messenger')}</dt><dd>{config.data.messengerTargetKey??c('notConfigured')}</dd></div><div><dt>{c('sso')}</dt><dd>{c(config.data.ssoConfigured?'configured':'notConfigured')}</dd></div><div><dt>{c('aiGeneration')}</dt><dd>{c(config.data.aiEnabled?'on':'off')}</dd></div><div><dt>{c('aiProvider')}</dt><dd>{c(config.data.aiProvider==='self_hosted'?'selfHosted':'openai')}</dd></div></dl><p className="platform-notice">{c('aiConfigNote')}</p><p className="platform-notice">{c('messengerNote')}</p></>}</ResourceState></section>}
 {section==='webhooks'&&<WebhookPanel session={session} config={config.data} configLoading={config.loading} configError={config.error} reloadConfig={config.reload}/>}
 {section==='identities'&&<IdentityPanel session={session} targets={config.data?.configuredTargets??[]}/>}
 {section==='imports'&&<IntegrationImport session={session} targets={config.data?.configuredTargets??[]}/>}
 </div>;
}

function ActionResult({action}:{action:ReturnType<typeof useAction>}) {const {c}=useIntegrationCopy();return <>{action.error&&<ErrorState message={action.error}/>} {action.success&&<p className="platform-success" role="status">{c('saved')}</p>}</>;}

function WebhookPanel({session,config,configLoading,configError,reloadConfig}:{session:Session;config:Config|undefined;configLoading:boolean;configError:string;reloadConfig:()=>void}) {
 const {c,locale}=useIntegrationCopy();const subscriptions=useResource<Webhook[]>('/integrations/webhooks');const deliveries=useResource<Delivery[]>('/integrations/deliveries');const action=useAction(session);
 const [name,setName]=useState('');const [target,setTarget]=useState('');const [selectedTopics,setTopics]=useState<string[]>([]);const [toggling,setToggling]=useState<Webhook>();const [page,setPage]=useState(1);
 useEffect(()=>{if(config?.configuredTargets.length&&!target)setTarget(config.configuredTargets[0]!);},[config,target]);
 useEffect(()=>{if(deliveries.data&&page>Math.max(1,Math.ceil(deliveries.data.length/10)))setPage(1);},[deliveries.data,page]);
 async function create(event:FormEvent){event.preventDefault();if(!selectedTopics.length||!target)return;const result=await action.run('/integrations/webhooks','POST',{name,targetKey:target,topics:selectedTopics});if(result){setName('');setTopics([]);subscriptions.reload();}}
 async function toggle(){if(!toggling)return;const result=await action.run(`/integrations/webhooks/${encodeURIComponent(toggling.id)}`,'PATCH',{active:!toggling.active});if(result){setToggling(undefined);subscriptions.reload();deliveries.reload();}}
 return <><section className="platform-card integrations-card"><div className="integrations-heading"><h2>{c('webhooks')}</h2><Button variant="ghost" size="small" onClick={subscriptions.reload}>{c('refresh')}</Button></div><ActionResult action={action}/><ResourceState loading={subscriptions.loading} error={subscriptions.error} retry={subscriptions.reload}>{!subscriptions.data?.length?<EmptyState title={c('empty')}/>:<div className="platform-table-wrap"><table className="platform-table integrations-table"><thead><tr><th>{c('name')}</th><th>{c('target')}</th><th>{c('topics')}</th><th>{c('deliveryStatus')}</th><th/></tr></thead><tbody>{subscriptions.data.map(item=><tr key={item.id}><td>{item.name}</td><td>{item.targetKey}</td><td>{item.topics.map(topic=>c(topics[topic as keyof typeof topics]??'topics')).join(', ')}</td><td><Badge tone={item.active?'green':'neutral'}>{c(item.active?'active':'inactive')}</Badge></td><td><Button disabled={action.busy} size="small" variant="secondary" onClick={()=>setToggling(item)}>{c(item.active?'disable':'enable')}</Button></td></tr>)}</tbody></table></div>}</ResourceState></section>
 <section className="platform-card integrations-card"><h2>{c('createSubscription')}</h2><p>{c('subscriptionNote')}</p><ResourceState loading={configLoading} error={configError} retry={reloadConfig}>{!config?.configuredTargets.length?<EmptyState title={c('noTargets')}/>:<form className="platform-form" onSubmit={event=>void create(event)}><fieldset disabled={action.busy}><label>{c('name')}<input required maxLength={100} value={name} onChange={event=>setName(event.target.value)}/></label><label>{c('target')}<select required value={target} onChange={event=>setTarget(event.target.value)}>{config.configuredTargets.map(key=><option key={key}>{key}</option>)}</select></label><fieldset className="integrations-topics"><legend>{c('topics')}</legend>{Object.entries(topics).map(([topic,label])=><label key={topic} className="platform-checkbox"><input type="checkbox" checked={selectedTopics.includes(topic)} onChange={()=>setTopics(selectedTopics.includes(topic)?selectedTopics.filter(item=>item!==topic):[...selectedTopics,topic])}/>{c(label)}</label>)}</fieldset><Button type="submit" disabled={!selectedTopics.length}>{action.busy?c('saving'):c('createSubscription')}</Button></fieldset></form>}</ResourceState></section>
 <section className="platform-card integrations-card"><div className="integrations-heading"><h2>{c('deliveries')}</h2><Button variant="ghost" size="small" onClick={deliveries.reload}>{c('refresh')}</Button></div><p>{c('deliveryNote')}</p><ResourceState loading={deliveries.loading} error={deliveries.error} retry={deliveries.reload}>{!deliveries.data?.length?<EmptyState title={c('empty')}/>:<><div className="platform-table-wrap"><table className="platform-table"><thead><tr><th>{c('subscription')}</th><th>{c('deliveryStatus')}</th><th>{c('attempts')}</th><th>{c('nextAttempt')}</th></tr></thead><tbody>{deliveries.data.slice((page-1)*10,page*10).map(item=><tr key={item.id}><td>{subscriptions.data?.find(subscription=>subscription.id===item.subscriptionId)?.name??item.subscriptionId}</td><td>{c(['pending','sending','delivered','failed','suppressed'].includes(item.status)?item.status as IntegrationCopyKey:'deliveryStatus')}</td><td>{item.attempts}/5</td><td>{['pending','sending','failed'].includes(item.status)&&item.attempts<5?deliveryTime(item.nextAttemptAt,locale):'—'}</td></tr>)}</tbody></table></div><Pager page={page} total={deliveries.data.length} limit={10} onChange={setPage}/></>}</ResourceState></section>
 <Modal title={c('confirmToggle')} description={c('subscriptionNote')} open={!!toggling} onClose={()=>setToggling(undefined)} busy={action.busy}><p>{toggling?.name}: {c(toggling?.active?'disable':'enable')}</p><div className="platform-actions"><Button disabled={action.busy} onClick={()=>void toggle()}>{c('apply')}</Button><Button variant="secondary" disabled={action.busy} onClick={()=>setToggling(undefined)}>{c('cancel')}</Button></div>{action.error&&<ErrorState message={action.error}/>}</Modal>
 </>;
}

function IdentityPanel({session,targets}:{session:Session;targets:string[]}) {
 const {c}=useIntegrationCopy();const [filter,setFilter]=useState('');const [debouncedFilter,setDebouncedFilter]=useState('');const [page,setPage]=useState(1);const [provider,setProvider]=useState('');const [entity,setEntity]=useState<'employee'|'event'>('employee');const [external,setExternal]=useState('');const [local,setLocal]=useState('');const [search,setSearch]=useState('');const [query,setQuery]=useState('');const [lookupPage,setLookupPage]=useState(1);const [removing,setRemoving]=useState<Identity>();const action=useAction(session);
 useEffect(()=>{const timer=setTimeout(()=>{setDebouncedFilter(filter.trim());setPage(1);},300);return()=>clearTimeout(timer);},[filter]);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search.trim());setLookupPage(1);},300);return()=>clearTimeout(timer);},[search]);
 const identities=useResource<Identity[]>(`/integrations/identities${debouncedFilter?`?providerKey=${encodeURIComponent(debouncedFilter)}`:''}`);
 const lookup=useResource<Lookup[]>(entity==='employee'?`/employees?q=${encodeURIComponent(query)}&page=${lookupPage}&limit=12`:`/events?q=${encodeURIComponent(query)}&includeInactive=true&page=${lookupPage}&limit=12`);
 useEffect(()=>{if(identities.data&&page>Math.max(1,Math.ceil(identities.data.length/15)))setPage(1);},[identities.data,page]);
 function reset(){setProvider('');setEntity('employee');setExternal('');setLocal('');setSearch('');action.clear();}
 function edit(item:Identity){setProvider(item.providerKey);setEntity(item.entityType);setExternal(item.externalId);setLocal(item.localId);setSearch('');setLookupPage(1);action.clear();}
 async function save(event:FormEvent){event.preventDefault();if(!local)return;const result=await action.run('/integrations/identities','PUT',{providerKey:provider.trim(),entityType:entity,externalId:external.trim(),localId:local});if(result)identities.reload();}
 async function remove(){if(!removing)return;const {localId:_,...body}=removing;const result=await action.run('/integrations/identities','DELETE',body);if(result){setRemoving(undefined);identities.reload();}}
 const options=(lookup.data??[]).map(item=>({id:entity==='employee'?item.id!:item.eventId!,name:entity==='employee'?item.name!:item.title!}));
 return <><section className="platform-card integrations-card"><h2>{c('saveMapping')}</h2><p>{c('mappingNote')}</p><form className="platform-form" onSubmit={event=>void save(event)}><fieldset disabled={action.busy}><div className="platform-fields"><label>{c('provider')}<input required maxLength={40} list="integration-providers" value={provider} onChange={event=>setProvider(event.target.value)}/><small>{c('providerHint')}</small></label><label>{c('entity')}<select value={entity} onChange={event=>{setEntity(event.target.value as 'employee'|'event');setLocal('');setSearch('');setLookupPage(1);}}><option value="employee">{c('employee')}</option><option value="event">{c('event')}</option></select></label></div><datalist id="integration-providers">{[...new Set([...targets,...(identities.data??[]).map(item=>item.providerKey)])].map(key=><option value={key} key={key}/>)}</datalist><label>{c('external')}<input required maxLength={200} value={external} onChange={event=>setExternal(event.target.value)}/></label><div className="integrations-record-picker"><label>{c('lookup')}<input type="search" maxLength={100} value={search} onChange={event=>setSearch(event.target.value)}/></label><ResourceState loading={lookup.loading} error={lookup.error} retry={lookup.reload}><label>{c('local')}<select required value={local} onChange={event=>setLocal(event.target.value)}><option value="">{c('choose')}</option>{local&&!options.some(item=>item.id===local)&&<option value={local}>{local}</option>}{options.map(item=><option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select></label><Pager page={lookupPage} total={lookup.meta?.total??options.length} limit={12} onChange={setLookupPage}/></ResourceState></div><div className="platform-actions"><Button type="submit" disabled={!local}>{action.busy?c('saving'):c('saveMapping')}</Button><Button variant="ghost" onClick={reset}>{c('cancelNew')}</Button></div></fieldset><ActionResult action={action}/></form></section>
 <section className="platform-card integrations-card"><div className="integrations-heading"><h2>{c('identities')}</h2><Button variant="ghost" size="small" onClick={identities.reload}>{c('refresh')}</Button></div><div className="platform-form"><label>{c('filter')}<input maxLength={40} value={filter} onChange={event=>setFilter(event.target.value)} placeholder={c('all')}/></label></div><p className="platform-hint">{c('mappingLimit')}</p><ResourceState loading={identities.loading} error={identities.error} retry={identities.reload}>{!identities.data?.length?<EmptyState title={c('empty')}/>:<><div className="platform-table-wrap"><table className="platform-table integrations-table"><thead><tr><th>{c('provider')}</th><th>{c('entity')}</th><th>{c('external')}</th><th>{c('local')}</th><th/></tr></thead><tbody>{identities.data.slice((page-1)*15,page*15).map(item=><tr key={`${item.providerKey}/${item.entityType}/${item.externalId}`}><td>{item.providerKey}</td><td>{c(item.entityType)}</td><td>{item.externalId}</td><td>{item.localId}</td><td><div className="platform-actions"><Button size="small" variant="secondary" disabled={action.busy} onClick={()=>edit(item)}>{c('edit')}</Button><Button size="small" variant="ghost" disabled={action.busy} onClick={()=>setRemoving(item)}>{c('remove')}</Button></div></td></tr>)}</tbody></table></div><Pager page={page} total={identities.data.length} limit={15} onChange={setPage}/></>}</ResourceState></section>
 <Modal title={c('removeTitle')} description={c('removeNote')} open={!!removing} onClose={()=>setRemoving(undefined)} busy={action.busy}><p>{removing?.providerKey} · {removing?.externalId} → {removing?.localId}</p><div className="platform-actions"><Button variant="danger" disabled={action.busy} onClick={()=>void remove()}>{c('remove')}</Button><Button variant="secondary" disabled={action.busy} onClick={()=>setRemoving(undefined)}>{c('cancel')}</Button></div>{action.error&&<ErrorState message={action.error}/>}</Modal>
 </>;
}

function IntegrationImport({session,targets}:{session:Session;targets:string[]}) {
 const {c}=useIntegrationCopy();const action=useAction(session);const [provider,setProvider]=useState('');const [messageId,setMessageId]=useState<string>(()=>crypto.randomUUID());const [data,setData]=useState<ImportData>();const [fileName,setFileName]=useState('');const [reading,setReading]=useState(false);const [fileError,setFileError]=useState('');const [snapshot,setSnapshot]=useState<ImportPayload>();const [lastAttempt,setLastAttempt]=useState<ImportPayload>();const [result,setResult]=useState<ImportResult>();const readVersion=useRef(0);
 useEffect(()=>()=>{readVersion.current++;},[]);
 const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
 async function readFile(file:File|undefined){if(!file||action.busy)return;const version=++readVersion.current;setData(undefined);setFileName(file.name);setFileError('');setResult(undefined);setLastAttempt(undefined);setSnapshot(undefined);setReading(true);action.clear();try{if(file.size>10*1024*1024)throw new Error(c('tooLarge'));if(!file.name.toLowerCase().endsWith('.json'))throw new Error(c('invalidFile'));const raw:unknown=JSON.parse((await file.text()).replace(/^\uFEFF/,''));if(!object(raw)||Object.keys(raw).some(key=>!['providerKey','messageId','history','employees'].includes(key))||(!raw.history&&!raw.employees)||('history'in raw&&(!Array.isArray(raw.history)||!raw.history.every(object)))||('employees'in raw&&(!object(raw.employees)||!object(raw.employees.meta)||!Array.isArray(raw.employees.employees)))||('providerKey'in raw&&typeof raw.providerKey!=='string')||('messageId'in raw&&typeof raw.messageId!=='string'))throw new Error(c('invalidFile'));if(version!==readVersion.current)return;setData({...(raw.history?{history:raw.history as Record<string,unknown>[]} :{}),...(raw.employees?{employees:raw.employees as Record<string,unknown>}: {})});if(typeof raw.providerKey==='string')setProvider(raw.providerKey);setMessageId(typeof raw.messageId==='string'?raw.messageId:crypto.randomUUID());}catch(error){if(version===readVersion.current)setFileError(error instanceof SyntaxError?c('invalidFile'):(error as Error).message);}finally{if(version===readVersion.current)setReading(false);}}
 function prepare(event:FormEvent){event.preventDefault();if(!data)return;const payload=JSON.parse(JSON.stringify({providerKey:provider.trim(),messageId:messageId.trim(),...data})) as ImportPayload;if(new TextEncoder().encode(JSON.stringify(payload)).byteLength>10*1024*1024){setFileError(c('tooLarge'));return;}setSnapshot(payload);}
 async function importPackage(payload:ImportPayload){setLastAttempt(payload);setSnapshot(undefined);setResult(undefined);const response=await action.run<ImportResult>('/integrations/import','POST',payload);if(response)setResult(response);}
 const profiles=data?.employees&&Array.isArray(data.employees.employees)?data.employees.employees.length:0;
 return <section className="platform-card integrations-card"><h2>{c('importTitle')}</h2><p>{c('importNote')}</p><form className="platform-form" onSubmit={prepare}><fieldset disabled={action.busy}><div className="integrations-file"><label>{c('file')}<input type="file" accept=".json,application/json" onChange={event=>{void readFile(event.target.files?.[0]);event.target.value='';}}/></label>{fileName&&<p className="platform-muted">{fileName}</p>}{reading&&<Loading label={c('reading')}/>}</div><p className="platform-hint">{c('formatHint')}</p>{fileError&&<ErrorState message={fileError}/>}<label>{c('provider')}<input required maxLength={40} list="import-providers" value={provider} onChange={event=>{setProvider(event.target.value);setResult(undefined);}}/><small>{c('providerHint')}</small></label><datalist id="import-providers">{targets.map(key=><option value={key} key={key}/>)}</datalist><label>{c('messageId')}<input required minLength={8} maxLength={160} value={messageId} onChange={event=>{setMessageId(event.target.value);setResult(undefined);}}/><small>{c('messageHint')}</small></label><Button size="small" variant="ghost" className="integrations-form-clear" onClick={()=>{setMessageId(crypto.randomUUID());setResult(undefined);}}>{c('generate')}</Button>{data&&<div className="integrations-summary"><span>{c('records')}: <strong>{data.history?.length??0}</strong></span><span>{c('employees')}: <strong>{profiles}</strong></span></div>}<Button type="submit" disabled={!data||reading||!!fileError}>{action.busy?c('saving'):c('confirmImport')}</Button></fieldset></form>
 {action.error&&<ErrorState message={action.error}/>} {lastAttempt&&action.error&&<div className="integrations-pending"><p>{c('immutableNote')}</p><p>{lastAttempt.providerKey} · {lastAttempt.messageId}</p><Button disabled={action.busy} onClick={()=>void importPackage(lastAttempt)}>{c('retryOriginal')}</Button></div>}
 {result&&<section className="platform-notice" role="status"><h3>{c(result.duplicate?'duplicate':'imported')}</h3><p>{c('employees')}: {result.counts.employees} · {c('records')}: {result.counts.history}</p><details><summary>{c('importHash')}</summary><code>{result.hash}</code></details></section>}
 <details><summary>{c('jsonExample')}</summary><pre className="integrations-json-example">{'{\n  "history": [\n    {\n      "record_id": "provider:unique-record-id",\n      "employee_id": "external-employee-id",\n      "event_id": "external-event-id",\n      "date": "2026-09-30",\n      "due_date": null,\n      "status": "completed",\n      "completion_pct": 100,\n      "score": 85,\n      "feedback_rating": 5,\n      "assigned_by": "self"\n    }\n  ]\n}'}</pre></details>
 <Modal title={c('confirmImport')} description={c('confirmImportNote')} open={!!snapshot} onClose={()=>setSnapshot(undefined)} busy={action.busy}><dl className="platform-value-list"><div><dt>{c('provider')}</dt><dd>{snapshot?.providerKey}</dd></div><div><dt>{c('messageId')}</dt><dd>{snapshot?.messageId}</dd></div><div><dt>{c('records')}</dt><dd>{snapshot?.history?.length??0}</dd></div></dl><div className="platform-actions"><Button disabled={action.busy} onClick={()=>{if(snapshot)void importPackage(snapshot);}}>{c('confirmImport')}</Button><Button variant="secondary" disabled={action.busy} onClick={()=>setSnapshot(undefined)}>{c('cancel')}</Button></div></Modal>
 </section>;
}
