import {useState} from 'react';
import {Link} from 'wouter';
import {Plus,RefreshCw,Trash2} from 'lucide-react';
import type {Session} from '../../api';
import {Badge,Button,EmptyState,ErrorState} from '../../components/ui';
import {useI18n} from '../../i18n';
import {Modal,ResourceState,useResource} from '../platform/common';
import type {Article,Locale,Topic} from '../guide/types';
import {semanticCopy} from '../guide/semantic.copy';
import {useSemanticRequest} from '../guide/semantic';
import './semantic.css';
type Query={key:string;q:string;locale:Locale;expectedArticleIds:string[]};
type QueryResult=Omit<Query,'key'> & {sqlArticleIds:string[];semanticArticleIds:string[];sqlRecallAt3:number;semanticRecallAt3:number};
type Evaluation={id:string;model:string;corpusHash:string;indexHash:string;queryCount:number;sqlRecallAt3:number;semanticRecallAt3:number;passed:boolean;results:QueryResult[];usageIds:string[]};
type Indexed={indexed:{articleId:string;revisionHash:string;charactersIndexed:number;truncated:boolean}[];model:string;usageId:string};
type Activation={enabled:boolean;evaluationId?:string;model?:string};
type Operation={kind:'index';body:{articleIds:string[]}}|{kind:'evaluate';body:{queries:Omit<Query,'key'>[]}}|{kind:'enable';body:{enabled:boolean;evaluationId?:string}}|{kind:'fresh'};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function emptyQuery(locale:Locale):Query{return {key:crypto.randomUUID(),q:'',locale,expectedArticleIds:[]};}
export function SemanticPanel({session}:{session:Session}){
 const {locale}=useI18n(),c=semanticCopy(locale);const admin=session.user.role==='admin';
 const [language,setLanguage]=useState<Locale>(locale),[selected,setSelected]=useState<string[]>([]),[queries,setQueries]=useState<Query[]>(()=>Array.from({length:10},()=>emptyQuery(locale)));
 const [operation,setOperation]=useState<Operation|null>(null),[acknowledged,setAcknowledged]=useState(false),[validation,setValidation]=useState(''),[indexed,setIndexed]=useState<Indexed|null>(null),[evaluation,setEvaluation]=useState<Evaluation|null>(null),[evaluationId,setEvaluationId]=useState(''),[activation,setActivation]=useState<Activation|null>(null);
 const request=useSemanticRequest(session),usage=useResource<{embeddingsEnabled?:boolean;embeddingsConfigured?:boolean;embeddingModel?:string|null;remainingUsd:number}>(admin?'/admin/ai/usage':null),topics=useResource<Topic[]>(admin?'/guide/topics?manage=true':null);
 const ru=useResource<Article[]>(admin?'/guide/articles?manage=true&locale=ru':null),kk=useResource<Article[]>(admin?'/guide/articles?manage=true&locale=kk':null),en=useResource<Article[]>(admin?'/guide/articles?manage=true&locale=en':null);
 const all=[...(ru.data??[]),...(kk.data??[]),...(en.data??[])],eligible=all.filter(a=>a.status==='published'&&a.ai_allowed&&a.reviewed_at&&a.expires_at&&new Date(a.expires_at).getTime()>Date.now()&&topics.data?.some(t=>t.id===a.topic_id&&t.active));
 const error=usage.error||topics.error||ru.error||kk.error||en.error,loading=usage.loading||topics.loading||ru.loading||kk.loading||en.loading;
 const canRun=usage.data?.embeddingsEnabled===true&&!loading&&!error;const validSelected=selected.filter(id=>eligible.some(a=>a.id===id));
 const titleFor=(id:string)=>all.find(a=>a.id===id)?.title??id;const percent=(n:number)=>new Intl.NumberFormat(locale,{style:'percent',maximumFractionDigits:1}).format(n);
 const reload=()=>{if(request.busy)return;usage.reload();topics.reload();ru.reload();kk.reload();en.reload();};
 const ask=(op:Operation)=>{request.clear();setAcknowledged(false);setOperation(op);};
 const updateQuery=(key:string,patch:Partial<Query>)=>{setValidation('');setEvaluation(null);setEvaluationId('');setQueries(items=>items.map(q=>q.key===key?{...q,...patch}:q));};
 const evaluate=()=>{const cleaned=queries.map(({key:_,...q})=>({...q,q:q.q.trim()}));const distinct=new Set(cleaned.map(q=>q.q.normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,' '))).size;if(cleaned.length<10||cleaned.length>30||distinct<10||cleaned.some(q=>q.q.length<2||q.q.length>300||q.expectedArticleIds.length<1||q.expectedArticleIds.length>3||q.expectedArticleIds.some(id=>!eligible.some(a=>a.id===id&&a.locale===q.locale)))){setValidation(c.validation);return;}setValidation('');ask({kind:'evaluate',body:{queries:cleaned}});};
 async function execute(){if(!operation||request.busy)return;if(operation.kind==='fresh'){request.newAttempt();setOperation(null);return;}if(operation.kind==='index'){const value=await request.run<Indexed>('/admin/semantic/index',operation.body);if(value){setIndexed(value);setEvaluation(null);setEvaluationId('');setActivation(null);setOperation(null);usage.reload();}}else if(operation.kind==='evaluate'){const value=await request.run<Evaluation>('/admin/semantic/evaluate',operation.body);if(value){setEvaluation(value);setEvaluationId(value.passed?value.id:'');setActivation(null);setOperation(null);usage.reload();}}else{const value=await request.run<Activation>('/admin/semantic/enable',operation.body);if(value){setActivation(value);setOperation(null);}}}
 if(!admin)return <EmptyState title={c.denied}/>;
 const operationDescription=operation?.kind==='index'?c.confirmIndex:operation?.kind==='evaluate'?c.confirmEvaluate:operation?.kind==='fresh'?c.freshConfirm:operation?.body.enabled?c.confirmEnable:c.confirmDisable;
 const articleLinks=(ids:string[])=>ids.length?<ul>{ids.map(id=><li key={id}><Link href={`/guide/articles/${encodeURIComponent(id)}`}>{titleFor(id)}</Link></li>)}</ul>:<span>—</span>;
 return <section className="semantic-panel" data-testid="semantic-panel"><div className="settings-section-heading"><div><h2>{c.title}</h2><p>{c.intro}</p></div><Button variant="secondary" disabled={request.busy||loading} onClick={reload}><RefreshCw size={16}/>{c.refresh}</Button></div><p className="semantic-note">{c.setup}</p><p className="semantic-note">{c.statusUnknown}</p>{usage.data?.embeddingModel&&<p className="semantic-note">{c.model}: {usage.data.embeddingModel}</p>}<ResourceState loading={loading} error={error} retry={reload}>
 {usage.data?.embeddingsEnabled!==true&&<p className="semantic-warning" role="status">{c.disabled}</p>}
 <fieldset disabled={request.busy||loading} className="semantic-sections">
 <section className="card"><h3>{c.index}</h3><p>{c.indexHint}</p><p>{c.indexLimit}</p><label className="semantic-field" htmlFor="semantic-language">{c.language}</label><select id="semantic-language" value={language} onChange={e=>setLanguage(e.target.value as Locale)}><option value="ru">Русский</option><option value="kk">Қазақша</option><option value="en">English</option></select><div className="semantic-article-options">{eligible.filter(a=>a.locale===language).map(a=><label key={a.id}><input type="checkbox" checked={validSelected.includes(a.id)} disabled={!canRun||(!validSelected.includes(a.id)&&validSelected.length>=10)} onChange={e=>setSelected(e.target.checked?[...validSelected,a.id]:validSelected.filter(id=>id!==a.id))}/><span><strong>{a.title}</strong><small>{c.version} {a.version} · {a.locale.toUpperCase()} {a.synthetic&&`· ${c.synthetic}`}</small></span></label>)}{!eligible.some(a=>a.locale===language)&&<EmptyState title={c.noEligible}/>}</div><div className="semantic-actions"><span>{c.selected}: {validSelected.length} / 10</span><Button disabled={!canRun||validSelected.length<1||validSelected.length>10} onClick={()=>ask({kind:'index',body:{articleIds:[...validSelected]}})} data-testid="semantic-index">{c.indexAction}</Button></div>{indexed&&<div className="semantic-result" role="status"><h4>{c.indexed}</h4><p>{c.model}: {indexed.model}</p><ul>{indexed.indexed.map(a=><li key={a.articleId}>{titleFor(a.articleId)} — {c.characters}: {a.charactersIndexed}{a.truncated&&<> · <Badge tone="warning">{c.truncated}</Badge></>}</li>)}</ul></div>}</section>
 <section className="card"><h3>{c.evaluation}</h3><p>{c.evaluationHint}</p><p>{c.privacy}</p><div className="semantic-queries">{queries.map((q,index)=><fieldset className="semantic-query" key={q.key}><legend>{c.question} {index+1}</legend><div className="semantic-query-top"><label htmlFor={`question-${q.key}`}>{c.question}</label><Button size="small" variant="ghost" disabled={queries.length<=10} aria-label={`${c.remove} ${c.question.toLowerCase()} ${index+1}`} onClick={()=>{setQueries(items=>items.filter(item=>item.key!==q.key));setValidation('');setEvaluation(null);setEvaluationId('');}}><Trash2 size={15}/></Button></div><textarea id={`question-${q.key}`} value={q.q} minLength={2} maxLength={300} rows={2} onChange={e=>updateQuery(q.key,{q:e.target.value})}/><label htmlFor={`language-${q.key}`}>{c.language}</label><select id={`language-${q.key}`} value={q.locale} onChange={e=>updateQuery(q.key,{locale:e.target.value as Locale,expectedArticleIds:[]})}><option value="ru">Русский</option><option value="kk">Қазақша</option><option value="en">English</option></select><label htmlFor={`expected-${q.key}`}>{c.expected}</label><select id={`expected-${q.key}`} value="" disabled={q.expectedArticleIds.length>=3} onChange={e=>{if(e.target.value)updateQuery(q.key,{expectedArticleIds:[...q.expectedArticleIds,e.target.value]});}}><option value="">{c.chooseArticle}</option>{eligible.filter(a=>a.locale===q.locale&&!q.expectedArticleIds.includes(a.id)).map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><ul className="semantic-selected">{q.expectedArticleIds.map(id=><li key={id}><span>{titleFor(id)}</span><Button size="small" variant="ghost" aria-label={`${c.remove}: ${titleFor(id)}`} onClick={()=>updateQuery(q.key,{expectedArticleIds:q.expectedArticleIds.filter(v=>v!==id)})}><Trash2 size={14}/></Button></li>)}</ul></fieldset>)}</div><div className="semantic-actions"><Button variant="secondary" disabled={queries.length>=30} onClick={()=>{setQueries(items=>[...items,emptyQuery(language)]);setEvaluation(null);setEvaluationId('');}}><Plus size={16}/>{c.addQuestion}</Button><Button disabled={!canRun} onClick={evaluate} data-testid="semantic-evaluate">{c.evaluate}</Button></div>{validation&&<p role="alert" className="semantic-validation">{validation}</p>}
 {evaluation&&<div className="semantic-result"><h4><Badge tone={evaluation.passed?'success':'warning'}>{evaluation.passed?c.passed:c.failed}</Badge></h4><p>{c.metric}</p><div className="semantic-metrics"><div><span>{c.sql}</span><strong>{percent(evaluation.sqlRecallAt3)}</strong></div><div><span>{c.semantic}</span><strong>{percent(evaluation.semanticRecallAt3)}</strong></div></div><p>{c.model}: {evaluation.model}</p><p>{c.evaluationId}: <code>{evaluation.id}</code></p><p>{c.representative}</p>{evaluation.results.map((row,index)=><details key={index}><summary>{index+1}. {row.q} · {row.locale.toUpperCase()}</summary><h5>{c.expected}</h5>{articleLinks(row.expectedArticleIds)}<h5>{c.sqlResults} · {percent(row.sqlRecallAt3)}</h5>{articleLinks(row.sqlArticleIds)}<h5>{c.semanticResults} · {percent(row.semanticRecallAt3)}</h5>{articleLinks(row.semanticArticleIds)}</details>)}</div>}
 </section>
 <section className="card"><h3>{c.activate}</h3><p>{c.criteria}</p><label htmlFor="semantic-evaluation">{c.evaluationId}</label><input id="semantic-evaluation" value={evaluationId} onChange={e=>setEvaluationId(e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" maxLength={36} autoComplete="off"/><p>{c.enableHint}</p><div className="semantic-actions"><Button disabled={!canRun||!uuid.test(evaluationId.trim())} onClick={()=>ask({kind:'enable',body:{enabled:true,evaluationId:evaluationId.trim()}})} data-testid="semantic-enable">{c.enable}</Button><Button variant="secondary" onClick={()=>ask({kind:'enable',body:{enabled:false}})}>{c.disable}</Button></div>{activation&&<p className="semantic-result" role="status">{activation.enabled?c.enabledResult:c.disabledResult}</p>}</section>
 </fieldset></ResourceState>
 <Modal open={Boolean(operation)} onClose={()=>setOperation(null)} busy={request.busy} title={c.title} description={operationDescription}><div className="semantic-confirm">{operation?.kind==='index'&&<ul>{operation.body.articleIds.map(id=><li key={id}>{titleFor(id)}</li>)}</ul>}{operation?.kind==='evaluate'&&<p>{c.question}: {operation.body.queries.length}</p>}{operation?.kind==='enable'&&operation.body.evaluationId&&<p>{c.evaluationId}: <code>{operation.body.evaluationId}</code></p>}{operation?.kind!=='fresh'&&<label className="semantic-acknowledge"><input type="checkbox" checked={acknowledged} onChange={e=>setAcknowledged(e.target.checked)} disabled={request.busy}/><span>{c.acknowledge}</span></label>}{request.error&&<><ErrorState message={request.error}/><p>{c.retryHint}</p>{!request.busy&&<Button variant="secondary" onClick={()=>setOperation({kind:'fresh'})}>{c.fresh}</Button>}</>}<div className="semantic-actions"><Button variant="secondary" disabled={request.busy} onClick={()=>setOperation(null)}>{c.cancel}</Button><Button disabled={request.busy||(operation?.kind!=='fresh'&&!acknowledged)} onClick={()=>void execute()}>{request.busy?c.working:c.confirm}</Button></div></div></Modal>
 </section>;
}
