import {useEffect,useRef,useState} from 'react';
import {Link} from 'wouter';
import {CalendarDays,Check,RefreshCw} from 'lucide-react';
import {api,type Session} from '../../api';
import {Badge,Button,ErrorState,Heading} from '../../components/ui';
import {useI18n} from '../../i18n';
import {dateText,Empty,Pager,ResourceState,safeInternalLink,useAction,useResource} from './common';
import {personalCopy} from './personal.copy';
type Notice={id:string;kind:string;title:string;body:string;link:string;readAt:string|null;createdAt:string};
type Preferences={inApp:boolean;messenger:boolean;reminders:boolean};
export function NotificationsPage({session}:{session:Session}){
 const {locale}=useI18n();const c=personalCopy[locale];const [page,setPage]=useState(1);const list=useResource<Notice[]>(session.user.employeeId?`/notifications?page=${page}&limit=20`:null);const prefs=useResource<Preferences>(session.user.employeeId?'/notification-preferences':null);const [draft,setDraft]=useState<Preferences|null>(null);const action=useAction(session);const preferenceAction=useAction(session);const [downloading,setDownloading]=useState(false);const [downloadError,setDownloadError]=useState('');
 useEffect(()=>{if(prefs.data)setDraft(prefs.data);},[prefs.data]);
 const downloadController=useRef<AbortController|null>(null);const downloadLock=useRef(false);
 useEffect(()=>()=>downloadController.current?.abort(),[]);
 async function download(){if(downloadLock.current)return;downloadLock.current=true;const request=new AbortController();downloadController.current=request;setDownloading(true);setDownloadError('');try{const result=await api<{content:string}>('/calendar',{signal:request.signal});if(request.signal.aborted)return;const url=URL.createObjectURL(new Blob([result.data.content],{type:'text/calendar;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='career-quest.ics';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){if(!request.signal.aborted)setDownloadError((e as Error).message);}finally{downloadLock.current=false;if(!request.signal.aborted)setDownloading(false);}}
 if(!session.user.employeeId)return <div className="platform-page"><Heading title={c.title}/><Empty title={c.noEmployee}/></div>;
 return <div className="platform-page" data-testid="notifications-page"><Heading title={c.title} subtitle={c.subtitle}/><div className="platform-grid"><section className="platform-card"><h2>{c.preferences}</h2><ResourceState loading={prefs.loading} error={prefs.error} retry={prefs.reload}>{draft&&<form className="platform-form" onSubmit={async event=>{event.preventDefault();await preferenceAction.run('/notification-preferences','PUT',draft);}}>{(['inApp','reminders','messenger'] as const).map(key=><label key={key} className="platform-checkbox"><input type="checkbox" disabled={preferenceAction.busy} checked={draft[key]} onChange={event=>{preferenceAction.clear();setDraft({...draft,[key]:event.target.checked});}}/>{c[key]}</label>)}<p className="platform-hint">{c.messengerHint}</p>{preferenceAction.error&&<ErrorState message={preferenceAction.error}/>}<div><Button type="submit" disabled={preferenceAction.busy}>{c.save}</Button></div>{preferenceAction.success&&<p className="platform-success" role="status">{c.saved}</p>}</form>}</ResourceState></section><section className="platform-card"><h2>{c.calendar}</h2><p>{c.calendarText}</p>{downloadError&&<ErrorState message={downloadError}/>}<Button variant="secondary" disabled={downloading} onClick={()=>void download()}><CalendarDays size={18}/>{c.download}</Button></section></div><section className="platform-card"><div className="section-heading"><h2>{c.notifications}</h2><Button variant="ghost" size="small" onClick={list.reload} aria-label={c.refresh}><RefreshCw size={16}/>{c.refresh}</Button></div>{action.error&&<ErrorState message={action.error}/>}<ResourceState loading={list.loading} error={list.error} retry={list.reload}>{list.data?.length?<>{list.data.map(notice=><article className={`platform-notification${notice.readAt?'':' unread'}`} key={notice.id}><div><h3>{notice.title}</h3><p>{notice.body}</p><small>{dateText(notice.createdAt,locale)}</small></div><div className="platform-actions"><Button size="small" variant="secondary" asChild><Link href={safeInternalLink(notice.link)}>{c.open}</Link></Button>{!notice.readAt?<Button size="small" variant="ghost" disabled={action.busy} onClick={async()=>{if(await action.run(`/notifications/${encodeURIComponent(notice.id)}/read`,'POST',{}))list.reload();}}><Check size={15}/>{c.read}</Button>:<Badge><span role="img" aria-label={locale==='ru'?'Прочитано':locale==='kk'?'Оқылды':'Read'}><Check size={12}/></span></Badge>}</div></article>)}<Pager page={page} total={list.meta?.total??0} limit={20} onChange={setPage}/></>:<Empty title={c.empty} text={c.emptyText}/>}</ResourceState></section></div>;
}
