import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowLeft, Plus, Trash2 } from 'lucide-react';
import type { Session } from '../../api';
import { Badge, Button, EmptyState, Heading, Loading } from '../../components/ui';
import { label, useCareerCopy } from './copy';
import { canManage, ConfirmDialog, contextQuery, EligibilityList, EmployeePicker, Notice, ResourceError, useDate, useEmployeeContext, useMutation, useRead } from './shared';
import { eventTypes, formats, grades, type CareerEvent, type CareerProfile, type EventInput, type EventPreview, type EventTranslation, type RoleProfile, type Skill } from './types';

const emptyEvent: EventInput = { eventId: '', title: '', description: '', type: 'course', format: 'self_paced', durationHours: 1, mandatory: false, isActive: true, targetRoles: [], targetGrades: [], effects: [], prerequisites: [], sessions: [] };
function toInput(event: CareerEvent): EventInput { return { eventId: event.eventId, title: event.title, description: event.description, type: event.type, format: event.format, durationHours: event.durationHours, mandatory: event.mandatory, isActive: event.isActive, targetRoles: [...event.targetRoles], targetGrades: [...event.targetGrades], effects: event.effects.map(item => ({ ...item })), prerequisites: event.prerequisites.map(item => ({ ...item })), sessions: event.sessions.map(item => ({ date: item.date, capacity: item.capacity })) }; }

export function EventsAdminPage({ session, eventId }: { session: Session; eventId?: string }) {
  const c = useCareerCopy();
  if (!canManage(session)) return <div className="career-page"><EmptyState title={c.unavailableEvent} description={c.readOnly} action={<Button asChild variant="secondary"><Link href="/events">{c.catalog}</Link></Button>} /></div>;
  return <EventEditor key={eventId ?? 'new'} session={session} eventId={eventId} />;
}

function EventEditor({ session, eventId }: { session: Session; eventId?: string }) {
  const c = useCareerCopy(); const date = useDate(); const [, navigate] = useLocation(); const { employeeId, choose } = useEmployeeContext(session);
  const existing = useRead<CareerEvent>(eventId ? `/events/${encodeURIComponent(eventId)}` : null); const skills = useRead<Skill[]>('/skills'); const roles = useRead<RoleProfile[]>('/role-profiles'); const profile = useRead<CareerProfile>(employeeId ? `/employees/${encodeURIComponent(employeeId)}` : null);
  const mutation = useMutation(session); const [draft, setDraft] = useState<EventInput>(emptyEvent); const [preview, setPreview] = useState<{ signature: string; data: EventPreview }>(); const [clientError, setClientError] = useState<Error>(); const [action, setAction] = useState<'save' | 'archive' | null>(null); const [choosing, setChoosing] = useState(false); const initialized = useRef(false); const form = useRef<HTMLFormElement>(null);
  useEffect(() => { if (existing.data && !initialized.current) { setDraft(toInput(existing.data)); initialized.current = true; } }, [existing.data]);
  const signature = JSON.stringify([draft, employeeId]); const checked = preview?.signature === signature ? preview.data : undefined;
  const update = <K extends keyof EventInput>(key: K, value: EventInput[K]) => { setDraft(current => ({ ...current, [key]: value })); setPreview(undefined); setClientError(undefined); mutation.clear(); };
  const names = Object.fromEntries((skills.data ?? []).map(skill => [skill.id, skill.name]));
  const validate = () => {
    if (!form.current?.reportValidity()) return false;
    if (!draft.targetRoles.length || !draft.targetGrades.length) { setClientError(new Error(c.audienceRequired)); return false; }
    if (new Set(draft.effects.map(item => item.skillId)).size !== draft.effects.length || new Set(draft.prerequisites.map(item => item.skillId)).size !== draft.prerequisites.length) { setClientError(new Error(c.duplicateSkills)); return false; }
    if (new Set(draft.sessions.map(item => item.date)).size !== draft.sessions.length) { setClientError(new Error(c.duplicateSessions)); return false; }
    setClientError(undefined); return true;
  };
  if (existing.error) return <ResourceError error={existing.error} retry={existing.reload} />;
  if (eventId && existing.loading) return <Loading />;
  if (skills.error || roles.error) return <ResourceError error={(skills.error ?? roles.error)!} retry={() => { skills.reload(); roles.reload(); }} />;
  if (skills.loading || roles.loading) return <Loading />;
  if (!roles.data?.length) return <EmptyState title={c.empty} action={<Button variant="secondary" onClick={roles.reload}>{c.retry}</Button>} />;
  return <div className="career-page"><Button asChild variant="ghost" size="small"><Link href={eventId ? `/events/${encodeURIComponent(eventId)}${contextQuery(employeeId)}` : `/events${contextQuery(employeeId)}`}><ArrowLeft size={16} />{c.catalog}</Link></Button><Heading title={eventId ? c.eventEditor : c.createEvent} subtitle={c.editorSub} action={eventId && <Button variant={existing.data?.isActive ? 'danger' : 'secondary'} onClick={() => { mutation.clear(); setAction('archive'); }}>{existing.data?.isActive ? c.archiveEvent : c.restoreEvent}</Button>} />
    <form ref={form} onSubmit={async event => { event.preventDefault(); if (!validate()) return; if (!employeeId) { setChoosing(true); return; } const atStart = signature; const response = await mutation.run<EventPreview>('POST', `/events/preview${contextQuery(employeeId)}`, draft); if (response) setPreview({ signature: atStart, data: response.data }); }}>
      <fieldset className="career-editor-fields" disabled={mutation.busy}>
      <section className="career-card"><div className="career-form-grid"><label className="career-field">{c.eventId}<input required maxLength={100} pattern={'[A-Za-z0-9_\\-]+'} readOnly={!!eventId} value={draft.eventId} onChange={event => update('eventId', event.target.value)} /></label><label className="career-field">{c.type}<select value={draft.type} onChange={event => update('type', event.target.value)}>{eventTypes.map(type => <option key={type} value={type}>{label(c, type)}</option>)}</select></label><label className="career-field career-field-wide">{c.title}<input required maxLength={300} value={draft.title} onChange={event => update('title', event.target.value)} /></label><label className="career-field career-field-wide">{c.description}<textarea aria-label={c.description} maxLength={10000} rows={5} value={draft.description} onChange={event => update('description', event.target.value)} /></label><label className="career-field">{c.format}<select value={draft.format} onChange={event => update('format', event.target.value)}>{formats.map(format => <option key={format} value={format}>{label(c, format)}</option>)}</select></label><label className="career-field">{c.duration}<input type="number" min={0.1} max={1000} step={0.1} required value={draft.durationHours || ''} onChange={event => update('durationHours', Number(event.target.value))} /></label></div><div className="career-filter-checks"><label className="career-check"><input type="checkbox" checked={draft.mandatory} onChange={event => update('mandatory', event.target.checked)} />{c.mandatory}</label><label className="career-check"><input type="checkbox" checked={draft.isActive} onChange={event => update('isActive', event.target.checked)} />{c.published}</label></div></section>
      <section className="career-card"><h2>{c.audience}</h2><div className="career-two-col"><fieldset className="career-checkbox-fieldset"><legend>{c.role}</legend>{[...new Set(roles.data?.map(item => item.role))].map(role => <label key={role} className="career-check"><input type="checkbox" checked={draft.targetRoles.includes(role)} onChange={event => update('targetRoles', event.target.checked ? [...draft.targetRoles, role] : draft.targetRoles.filter(item => item !== role))} />{role}</label>)}</fieldset><fieldset className="career-checkbox-fieldset"><legend>{c.grade}</legend>{grades.map(grade => <label key={grade} className="career-check"><input type="checkbox" checked={draft.targetGrades.includes(grade)} onChange={event => update('targetGrades', event.target.checked ? [...draft.targetGrades, grade] : draft.targetGrades.filter(item => item !== grade))} />{grade}</label>)}</fieldset></div></section>
      <section className="career-card"><div className="career-card-heading"><h2>{c.effects}</h2><Button size="small" variant="secondary" disabled={draft.effects.length >= 200} onClick={() => update('effects', [...draft.effects, { skillId: '', gain: 1, maxLevel: 5 }])}><Plus size={15} />{c.add}</Button></div>{!draft.effects.length && <p className="career-muted">{c.noEffects}</p>}{draft.effects.map((effect, index) => <div key={index} className="career-editor-row"><label className="career-field">{c.skill}<select aria-label={c.skill} required value={effect.skillId} onChange={event => update('effects', draft.effects.map((item, i) => i === index ? { ...item, skillId: event.target.value } : item))}><option value="">—</option>{skills.data?.map(skill => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label><label className="career-field">{c.gain}<input required type="number" min={1} max={5} step={1} value={effect.gain} onChange={event => update('effects', draft.effects.map((item, i) => i === index ? { ...item, gain: Number(event.target.value) } : item))} /></label><label className="career-field">{c.maxLevel}<input required type="number" min={0} max={5} step={1} value={effect.maxLevel} onChange={event => update('effects', draft.effects.map((item, i) => i === index ? { ...item, maxLevel: Number(event.target.value) } : item))} /></label><Button variant="ghost" size="small" aria-label={`${c.remove}: ${index + 1}`} onClick={() => update('effects', draft.effects.filter((_, i) => i !== index))}><Trash2 size={16} /></Button></div>)}</section>
      <section className="career-card"><div className="career-card-heading"><h2>{c.prerequisites}</h2><Button size="small" variant="secondary" disabled={draft.prerequisites.length >= 200} onClick={() => update('prerequisites', [...draft.prerequisites, { skillId: '', minLevel: 1 }])}><Plus size={15} />{c.add}</Button></div>{!draft.prerequisites.length && <p className="career-muted">{c.noPrerequisites}</p>}{draft.prerequisites.map((prerequisite, index) => <div key={index} className="career-editor-row career-editor-row-short"><label className="career-field">{c.skill}<select aria-label={c.skill} required value={prerequisite.skillId} onChange={event => update('prerequisites', draft.prerequisites.map((item, i) => i === index ? { ...item, skillId: event.target.value } : item))}><option value="">—</option>{skills.data?.map(skill => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></label><label className="career-field">{c.minLevel}<input required type="number" min={0} max={5} step={1} value={prerequisite.minLevel} onChange={event => update('prerequisites', draft.prerequisites.map((item, i) => i === index ? { ...item, minLevel: Number(event.target.value) } : item))} /></label><Button variant="ghost" size="small" aria-label={`${c.remove}: ${index + 1}`} onClick={() => update('prerequisites', draft.prerequisites.filter((_, i) => i !== index))}><Trash2 size={16} /></Button></div>)}</section>
      <section className="career-card"><div className="career-card-heading"><h2>{c.sessions}</h2><Button size="small" variant="secondary" disabled={draft.sessions.length >= 500} onClick={() => update('sessions', [...draft.sessions, { date: '', capacity: null }])}><Plus size={15} />{c.add}</Button></div><p className="career-muted">{c.snapshotHelp}</p>{draft.sessions.map((item, index) => <div key={index} className="career-editor-row career-editor-row-short"><label className="career-field">{c.date}<input required type="date" value={item.date} onChange={event => update('sessions', draft.sessions.map((session, i) => i === index ? { ...session, date: event.target.value } : session))} /></label><label className="career-field">{c.capacity}<input type="number" min={1} max={100000} step={1} value={item.capacity ?? ''} onChange={event => update('sessions', draft.sessions.map((session, i) => i === index ? { ...session, capacity: event.target.value === '' ? null : Number(event.target.value) } : session))} /></label><Button variant="ghost" size="small" aria-label={`${c.remove}: ${index + 1}`} onClick={() => update('sessions', draft.sessions.filter((_, i) => i !== index))}><Trash2 size={16} /></Button></div>)}</section>
      <section className="career-card"><h2>{c.previewEmployee}</h2><div className="career-context-control"><span>{profile.data?.name ?? employeeId ?? '—'}{profile.data?.asOfDate && <small> · {c.asOf}: {date(profile.data.asOfDate)}</small>}</span><Button variant="secondary" size="small" onClick={() => setChoosing(value => !value)}>{c.chooseEmployee}</Button></div>{profile.error && <ResourceError error={profile.error} retry={profile.reload} />}{(choosing || !employeeId) && <EmployeePicker onChoose={id => { choose(id); setChoosing(false); setPreview(undefined); }} />}<p className="career-muted">{c.previewHelp}</p>{clientError && <ResourceError error={clientError} />}{mutation.error && action === null && <ResourceError error={mutation.error} />}<div className="career-actions"><Button type="submit" variant="secondary" disabled={!employeeId || mutation.busy}>{mutation.busy ? c.saving : c.preview}</Button><Button disabled={!checked || mutation.busy} onClick={() => { if (validate()) { mutation.clear(); setAction('save'); } }}>{c.saveEvent}</Button></div></section>
      </fieldset>
    </form>
    {checked && <section className="career-card"><Notice success>{c.previewReady}</Notice><EligibilityList eligibility={checked.eligibility} names={names} /><details><summary>{c.effects}</summary><ul className="career-fact-list">{draft.effects.map(effect => <li key={effect.skillId}><strong>{names[effect.skillId] ?? effect.skillId}</strong><span>{c.effective}: {checked.expectedLevels[effect.skillId] ?? '—'}</span></li>)}</ul></details></section>}
    {eventId && <TranslationEditor eventId={eventId} session={session} />}
    <ConfirmDialog open={action !== null} title={action === 'archive' ? (existing.data?.isActive ? c.archiveEvent : c.restoreEvent) : c.saveEvent} busy={mutation.busy} error={mutation.error} disabled={action === 'save' && !checked} onClose={() => setAction(null)} onConfirm={async () => { const response = action === 'archive' ? await mutation.run('PATCH', `/events/${encodeURIComponent(eventId!)}`, { isActive: !existing.data?.isActive }) : await mutation.run(eventId ? 'PUT' : 'POST', eventId ? `/events/${encodeURIComponent(eventId)}` : '/events', draft); if (response) { setAction(null); navigate(`/events/${encodeURIComponent(eventId ?? draft.eventId)}${contextQuery(employeeId)}`); } }}><p><strong>{draft.title}</strong></p>{action === 'archive' && existing.data?.isActive ? <p>{c.archiveHelp}</p> : <p>{c.previewHelp}</p>}</ConfirmDialog>
  </div>;
}

function TranslationEditor({ eventId, session }: { eventId: string; session: Session }) {
  const c = useCareerCopy(); const mutation = useMutation(session); const translations = useRead<EventTranslation[]>(`/events/${encodeURIComponent(eventId)}/translations`); const [locale, setLocale] = useState<'ru' | 'kk' | 'en'>('ru'); const [drafts, setDrafts] = useState({ ru: { title: '', description: '' }, kk: { title: '', description: '' }, en: { title: '', description: '' } }); const [confirmation, setConfirmation] = useState(false); const [saved, setSaved] = useState(false); const initialized = useRef(false);
  useEffect(() => { if (!translations.data || initialized.current) return; setDrafts(current => { const next = { ...current }; for (const item of translations.data!) next[item.locale] = { title: item.title, description: item.description }; return next; }); initialized.current = true; }, [translations.data]);
  const draft = drafts[locale];
  return <section className="career-card"><h2>{c.translations}</h2><p className="career-muted">{c.translationHelp}</p>{saved && <Notice success>{c.saved}</Notice>}{translations.error ? <ResourceError error={translations.error} retry={translations.reload} /> : translations.loading ? <Loading /> : <form onSubmit={event => { event.preventDefault(); mutation.clear(); setConfirmation(true); }}><label className="career-field">{c.language}<select aria-label={c.language} value={locale} onChange={event => setLocale(event.target.value as typeof locale)}><option value="ru">Русский</option><option value="kk">Қазақша</option><option value="en">English</option></select></label><label className="career-field">{c.title}<input required maxLength={300} value={draft.title} onChange={event => setDrafts(current => ({ ...current, [locale]: { ...current[locale], title: event.target.value } }))} /></label><label className="career-field">{c.description}<textarea aria-label={c.description} required maxLength={10000} rows={5} value={draft.description} onChange={event => setDrafts(current => ({ ...current, [locale]: { ...current[locale], description: event.target.value } }))} /></label><Button type="submit" disabled={mutation.busy}>{c.approveTranslation}</Button></form>}<ConfirmDialog open={confirmation} title={c.approveTranslation} busy={mutation.busy} error={mutation.error} onClose={() => setConfirmation(false)} onConfirm={async () => { const response = await mutation.run('PUT', `/events/${encodeURIComponent(eventId)}/translations/${locale}`, draft); if (response) { setConfirmation(false); setSaved(true); translations.reload(); } }}><p>{locale.toLocaleUpperCase()} · {draft.title}</p><p>{c.translationHelp}</p></ConfirmDialog></section>;
}
