import {useRef,useState} from 'react';
import {Link} from 'wouter';
import {ArrowLeft} from 'lucide-react';
import {api,type Session} from '../../api';
import {Button,EmptyState,Heading} from '../../components/ui';
import {Confirm,GuideMutationScope,MutationNotice,useGuideCopy,useMutation} from './helpers';
import {ArticlesEditor} from './ArticleEditor';
import {ContactsEditor,FeedbackEditor,RoutingEditor,TopicsEditor} from './DirectoryEditors';
import './guide.css';
function SeedButton({session,onSeeded}:{session:Session;onSeeded:()=>void}){const {c}=useGuideCopy();const mutation=useMutation();const [open,setOpen]=useState(false);const [count,setCount]=useState<number|null>(null);return <div className="guide-toolbar"><Button variant="secondary" disabled={mutation.busy} onClick={()=>setOpen(true)}>{c.seed}</Button>{count!==null&&<span role="status">{c.seedCreated}: {count}</span>}<Confirm open={open} onOpenChange={setOpen} title={c.seed} description={c.seedDescription} action={c.seed} busy={mutation.busy} onConfirm={()=>void mutation.run(async()=>{const response=await api<{created:number}>('/guide/demo-seed',{method:'POST',csrf:session.csrfToken});setCount(response.data.created);setOpen(false);onSeeded();})}><MutationNotice mutation={mutation}/></Confirm></div>;}
export function GuideAdminPage({session}:{session:Session}){const {c}=useGuideCopy();const lock=useRef(false);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const [tab,setTab]=useState<'articles'|'topics'|'contacts'|'routing'|'feedback'>('articles');if(!['hr','admin'].includes(session.user.role))return <div className="guide-page"><Heading title={c.manage}/><EmptyState title={c.denied}/></div>;return <GuideMutationScope.Provider value={{lock,setBusy}}><div className="guide-page guide-manage"><Link className="guide-back" href="/guide"><ArrowLeft size={16}/>{c.back}</Link><Heading title={c.manage} subtitle={c.manageSub}/><nav className="guide-tabs" aria-label={c.manage}>{(['articles','topics','contacts','routing','feedback'] as const).map(value=><button key={value} className={value===tab?'is-active':''} aria-current={tab===value?'page':undefined} disabled={busy} onClick={()=>setTab(value)}>{c[value]}</button>)}</nav><fieldset disabled={busy}>{session.user.role==="admin"&&session.user.demo&&<SeedButton session={session} onSeeded={()=>setRevision(value=>value+1)}/>}<div key={revision}>{tab==='articles'?<ArticlesEditor session={session}/>:tab==='topics'?<TopicsEditor session={session}/>:tab==='contacts'?<ContactsEditor session={session}/>:tab==='routing'?<RoutingEditor session={session}/>:<FeedbackEditor session={session}/>}</div></fieldset></div></GuideMutationScope.Provider>;
}
