import {useEffect,useState} from 'react';
import {Link} from 'wouter';
import {Search,SlidersHorizontal} from 'lucide-react';
import type {Session} from '../../api';
import {Button,EmptyState,Heading} from '../../components/ui';
import {ArticleCard,AsyncState,useGuideCopy,useResource} from './helpers';
import type {Article,Context,Topic} from './types';
import './guide.css';
import {TicketsPanel} from './TicketsPanel';
import {SemanticSearch} from './SemanticSearch';
export function GuidePage({session}:{session:Session}){const {c,locale}=useGuideCopy();const [query,setQuery]=useState('');const [debounced,setDebounced]=useState('');const [topic,setTopic]=useState('');const [context,setContext]=useState<Context|''>('');useEffect(()=>{const id=setTimeout(()=>setDebounced(query.trim()),250);return()=>clearTimeout(id);},[query]);const topics=useResource<Topic[]>('/guide/topics');const params=new URLSearchParams({locale,q:debounced,...(topic?{topicId:topic}:{})});const articles=useResource<Article[]>(`/guide/articles?${params}`);const hints=useResource<Article[]>(context?`/guide/hints?${new URLSearchParams({context,locale})}`:null);return <div className="guide-page"><Heading title={c.guide} subtitle={c.guideSub} action={['hr','admin'].includes(session.user.role)?<Button asChild variant="secondary"><Link href="/guide/manage"><SlidersHorizontal size={16}/>{c.manage}</Link></Button>:undefined}/><div className="guide-searchbar"><label className="guide-search"><Search size={18}/><input aria-label={c.search} placeholder={c.search} value={query} maxLength={300} onChange={e=>setQuery(e.target.value)}/></label><label className="sr-only" htmlFor="guide-topic">{c.topic}</label><select id="guide-topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">{c.allTopics}</option>{topics.data?.map(item=><option key={item.id} value={item.id}>{item.category} · {item.slug}</option>)}</select></div>{Boolean(topics.error)&&<AsyncState resource={topics}>{null}</AsyncState>}<div className="guide-context"><label htmlFor="guide-context">{c.context}</label><select id="guide-context" value={context} onChange={e=>setContext(e.target.value as Context|'')}><option value="">{c.noContext}</option>{(['onboarding','review','role_change','learning_start','learning_complete'] as const).map(value=><option key={value} value={value}>{c[value]}</option>)}</select></div>{context&&<section className="guide-hints"><h2>{c.hints}</h2><AsyncState resource={hints}>{hints.data?.length?<div className="guide-article-grid">{hints.data.map(article=><ArticleCard key={article.id} article={article}/>)}</div>:<EmptyState title={c.noArticles}/>}</AsyncState></section>}<section aria-label={c.articles}><AsyncState resource={articles}>{articles.data?.length?<div className="guide-article-grid">{articles.data.map(article=><ArticleCard key={article.id} article={article}/>)}</div>:<EmptyState title={c.noArticles} description={c.noArticlesSub}/>}</AsyncState></section><SemanticSearch session={session}/><TicketsPanel session={session}/></div>;}
