import {useState} from 'react';
import {Link} from 'wouter';
import {ArrowLeft,BookOpen} from 'lucide-react';
import {api,type Session} from '../../api';
import {Badge,Button,Heading} from '../../components/ui';
import {AsyncState,ContactList,Field,MutationNotice,Resources,date,useGuideCopy,useMutation,useResource} from './helpers';
import type {Article,FeedbackKind} from './types';
import './guide.css';
function ArticleContent({article,session}:{article:Article;session:Session}){const {c,locale}=useGuideCopy();const [kind,setKind]=useState<FeedbackKind>('helpful');const [comment,setComment]=useState('');const mutation=useMutation();return <><Heading title={article.title} subtitle={article.summary}/><div className="guide-inline guide-meta"><Badge>{article.category||c.guide}</Badge><span>{c.version} {article.version}</span><span>{c.reviewed}: {date(article.reviewed_at,locale)}</span><span>{c.expires}: {date(article.expires_at,locale)}</span>{article.sensitivity==='sensitive'&&<Badge>{c.sensitive}</Badge>}</div>{article.synthetic&&<div className="info-notice">{c.syntheticNote}</div>}<div className="guide-reading-layout"><article className="guide-reading card"><h2>{c.applies}</h2><p className="guide-text">{article.applies_when}</p><p className="guide-body">{article.body}</p>{article.steps.length>0&&<><h2>{c.steps}</h2><ol className="guide-steps-list">{article.steps.map((step,index)=><li key={index}>{step}</li>)}</ol></>}{article.resources.length>0&&<><h2>{c.sources}</h2><Resources resources={article.resources}/></>}{article.tags.length>0&&<div className="guide-inline">{article.tags.map(tag=><Badge key={tag}>{tag}</Badge>)}</div>}</article><aside className="guide-aside"><h2>{c.contacts}</h2><ContactList contacts={article.contacts??[]}/></aside></div><section className="card guide-feedback"><h2>{c.feedbackTitle}</h2>{mutation.success?<p className="guide-success" role="status">{c.feedbackSent}</p>:<form onSubmit={event=>{event.preventDefault();void mutation.run(async()=>{await api(`/guide/articles/${encodeURIComponent(article.id)}/feedback`,{method:'POST',csrf:session.csrfToken,body:{kind,comment:comment.trim()}});});}}><fieldset disabled={mutation.busy}><div className="guide-feedback-kinds">{(['helpful','unhelpful','outdated','wrong_contact','incorrect'] as const).map(value=><label key={value}><input type="radio" name="feedback-kind" value={value} checked={kind===value} onChange={()=>setKind(value)}/>{c[value]}</label>)}</div><Field label={c.comment}><textarea value={comment} maxLength={2000} rows={3} onChange={e=>setComment(e.target.value)}/></Field><MutationNotice mutation={mutation}/><Button type="submit" disabled={mutation.busy}>{mutation.busy?c.saving:c.sendFeedback}</Button></fieldset></form>}</section></>;}
export function GuideArticlePage({session,articleId}:{session:Session;articleId:string}){const {c}=useGuideCopy();const article=useResource<Article>(`/guide/articles/${encodeURIComponent(articleId)}`);return <div className="guide-page"><Link className="guide-back" href="/guide"><ArrowLeft size={16}/>{c.back}</Link><AsyncState resource={article}>{article.data&&<ArticleContent key={article.data.id} article={article.data} session={session}/>}</AsyncState></div>;}
