import {cloneElement,createContext,isValidElement,useContext,useEffect,useId,useRef,useState,type MutableRefObject,type ReactElement,type ReactNode} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Link} from 'wouter';
import {BookOpen,ExternalLink,ShieldCheck,X} from 'lucide-react';
import {api,ApiError,type Role} from '../../api';
import {Badge,Button,EmptyState,ErrorState,Loading} from '../../components/ui';
import {useI18n} from '../../i18n';
import {guideCopy,type GuideCopy} from './copy';
import type {Article,GuideContact,Locale} from './types';
export const GuideMutationScope=createContext<{lock:MutableRefObject<boolean>;setBusy:(v:boolean)=>void}|null>(null);
export function useGuideCopy(){const {locale}=useI18n();return {locale,c:guideCopy(locale)};}
export function errorText(error:unknown,c:GuideCopy){if(error instanceof ApiError){if(error.code==='VERIFIED_CONTACT_REQUIRED')return c.verifiedContactRequired;if(error.code==='INVALID_EXPIRY')return c.expiryInvalid;if(error.code==='IMMUTABLE_VERSION')return c.immutable;if(['MESSAGE_PROCESSING','THREAD_BUSY'].includes(error.code))return c.processing;if(error.status===404)return c.unavailable;if(error.status===429)return c.limit;if(error.status===409)return c.conflict;if(error.status===400)return c.required;return error.message||c.error;}return error instanceof Error&&error.name==='GuideValidation'?error.message:c.error;}
export function invalid(message:string):never {const error=new Error(message);error.name='GuideValidation';throw error;}
export function useResource<T>(path:string|null){const [revision,setRevision]=useState(0);const [state,setState]=useState<{path:string|null;data:T|null;loading:boolean;error:unknown}>({path:null,data:null,loading:Boolean(path),error:null});useEffect(()=>{if(!path){setState({path:null,data:null,loading:false,error:null});return;}const controller=new AbortController();setState({path,data:null,loading:true,error:null});api<T>(path,{signal:controller.signal}).then(({data})=>{if(!controller.signal.aborted)setState({path,data,loading:false,error:null});}).catch(error=>{if(!controller.signal.aborted)setState({path,data:null,loading:false,error});});return()=>controller.abort();},[path,revision]);return {...(state.path===path?state:{path,data:null,loading:Boolean(path),error:null}),reload:()=>setRevision(value=>value+1)};}
export function useMutation(){const scope=useContext(GuideMutationScope);const lock=useRef(false);const mounted=useRef(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const [success,setSuccess]=useState(false);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;}},[]);return {busy,error,success,clear:()=>{setError(null);setSuccess(false);},run:async (task:()=>Promise<void>)=>{if(lock.current||scope?.lock.current)return;lock.current=true;if(scope){scope.lock.current=true;scope.setBusy(true);}setBusy(true);setError(null);setSuccess(false);try{await task();if(mounted.current)setSuccess(true);}catch(e){if(mounted.current)setError(e);}finally{lock.current=false;if(scope){scope.lock.current=false;scope.setBusy(false);}if(mounted.current)setBusy(false);}}};}
export function AsyncState({resource,children}:{resource:{loading:boolean;error:unknown;reload:()=>void};children:ReactNode}){const {c}=useGuideCopy();return resource.loading?<Loading/>:resource.error?<ErrorState message={errorText(resource.error,c)} retry={resource.reload}/>:<>{children}</>;}
export function MutationNotice({mutation}:{mutation:{error:unknown;success:boolean}}){const {c}=useGuideCopy();return <>{mutation.error?<ErrorState message={errorText(mutation.error,c)}/>:mutation.success?<p className="guide-success" role="status"><ShieldCheck size={16}/>{c.saved}</p>:null}</>;}
export const roles:Role[]=['employee','manager','hr','admin'];
export function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){const generated=useId();const element=isValidElement(children)?children as ReactElement<{id?:string;'aria-describedby'?:string}>:null;const id=element?.props.id??generated;return <div className="guide-field"><label htmlFor={id}>{label}</label>{element?cloneElement(element,{id,...(hint?{'aria-describedby':`${id}-hint`}:{})}):children}{hint&&<small id={`${id}-hint`}>{hint}</small>}</div>;}
export function Check({label,checked,onChange,disabled=false}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="guide-check"><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;}
export function RoleFields({value,onChange,disabled=false}:{value:Role[];onChange:(r:Role[])=>void;disabled?:boolean}){const {c}=useGuideCopy();return <fieldset className="guide-roles" disabled={disabled}><legend>{c.visibility}</legend>{roles.map(role=><Check key={role} label={c[role]} checked={value.includes(role)} onChange={checked=>onChange(checked?[...value,role]:value.filter(item=>item!==role))}/>)}</fieldset>;}
export function Confirm({open,onOpenChange,title,description,action,onConfirm,busy=false,danger=false,disabled=false,children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;action:string;onConfirm:()=>void;busy?:boolean;danger?:boolean;disabled?:boolean;children?:ReactNode}){const {c}=useGuideCopy();return <Dialog.Root open={open} onOpenChange={value=>{if(!busy)onOpenChange(value);}}><Dialog.Portal><Dialog.Overlay className="guide-overlay"/><Dialog.Content className="guide-modal"><Dialog.Title>{title}</Dialog.Title><Dialog.Description>{description}</Dialog.Description>{children}<div className="guide-actions"><Dialog.Close asChild><Button variant="secondary" disabled={busy}>{c.cancel}</Button></Dialog.Close><Button variant={danger?'danger':'primary'} disabled={busy||disabled} onClick={onConfirm}>{busy?c.saving:action}</Button></div><Dialog.Close asChild><button className="guide-close" aria-label={c.close} disabled={busy}><X size={18}/></button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;}
export function date(value:string|null|undefined,locale:Locale){if(!value)return '—';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?'—':new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(parsed);}
export function localDateTime(value?:string|null){const d=value?new Date(value):new Date(Date.now()+90*86400000);if(Number.isNaN(d.getTime()))return '';return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function lines(value:string){return value.split('\n').map(s=>s.trim()).filter(Boolean);}
export function httpsUrl(value:string){try{return new URL(value).protocol==='https:'?value:null;}catch{return null;}}
export function internalHref(value:string){return /^\/(guide\/articles\/|employees\/)[\w%/-]+$/.test(value)?value:null;}
export function ArticleCard({article}:{article:Article}){const {c,locale}=useGuideCopy();return <Link href={`/guide/articles/${encodeURIComponent(article.id)}`} className="guide-article-card"><div className="guide-card-top"><BookOpen size={20}/><span>{article.category||c.guide}</span>{article.synthetic&&<Badge tone="demo">{c.synthetic}</Badge>}</div><h2>{article.title}</h2><p>{article.summary}</p><div className="guide-card-foot"><span>{c.reviewed}: {date(article.reviewed_at,locale)}</span><span>{c.open} →</span></div></Link>;}
export function ContactList({contacts}:{contacts:GuideContact[]}){const {c,locale}=useGuideCopy();return <div className="guide-contact-list">{contacts.length?contacts.map((contact,index)=>{let href:string|null=null;if(!contact.synthetic){if(contact.channel==='url')href=httpsUrl(contact.value);if(contact.channel==='email'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.value))href=`mailto:${contact.value}`;if(contact.channel==='phone'&&/^\+?[\d ()-]{5,30}$/.test(contact.value))href=`tel:${contact.value.replace(/[ ()-]/g,'')}`;}return <section className="guide-contact" key={`${contact.id}-${contact.topicId}-${index}`}><div className="guide-inline"><h3>{contact.label}</h3>{contact.synthetic&&<Badge tone="demo">{c.demo}</Badge>}{contact.confidential&&<Badge>{c.confidential}</Badge>}{contact.urgency==='urgent'&&<Badge tone="warning">{c.urgent}</Badge>}</div><p>{contact.description}</p>{href?<a href={href} target={contact.channel==='url'?'_blank':undefined} rel="noopener noreferrer">{contact.value}<ExternalLink size={13}/></a>:<strong className="guide-contact-value">{contact.value}</strong>}<small>{c[contact.priority]} · {c.reviewed}: {date(contact.verifiedAt,locale)} · {c.expires}: {date(contact.expiresAt,locale)}</small></section>}):<EmptyState title={c.noContacts} description={c.noContactsSub}/>}</div>;}
export function Resources({resources}:{resources:Article['resources']}){return <ul className="guide-resources">{resources.map((resource,index)=>{const url=httpsUrl(resource.url);return <li key={index}>{url?<a href={url} target="_blank" rel="noopener noreferrer">{resource.label}<ExternalLink size={14}/></a>:resource.label}</li>})}</ul>;}
