import { useEffect, useState, type FormEvent } from 'react';
import type { Session } from '../../api';
import { Button, ErrorState } from '../../components/ui';
import { useGrowthCopy } from './copy';
import { EventPicker, Field, ForecastView, GoalSelect, MutationNotice, Panel, QueryState, Status, goalValue, useMutation, useQuery } from './shared';
import type { Forecast, Plan, PlanSummary, Preferences, RoleProfile, Skill } from './types';

export function Plans({ session }: { session: Session }) {
  const { c } = useGrowthCopy();
  const preferences = useQuery<Preferences>('/me/preferences'); const plans = useQuery<PlanSummary[]>('/me/plans'); const profiles = useQuery<RoleProfile[]>('/role-profiles'); const skills = useQuery<Skill[]>('/skills');
  const [selected, setSelected] = useState(''); const detail = useQuery<Plan>(selected ? `/me/plans/${encodeURIComponent(selected)}` : null);
  const [weeklyHours, setHours] = useState(4); const [formats, setFormats] = useState<string[]>(['online','offline','self_paced']); const [horizonDays, setHorizon] = useState(90); const [goal, setGoal] = useState(''); const [formatError, setFormatError] = useState(false); const [confirmArchive, setConfirmArchive] = useState(false);
  const prefMutation = useMutation(session); const planMutation = useMutation(session); const detailMutation = useMutation(session);
  useEffect(() => { if (preferences.data) { setHours(preferences.data.weeklyHours); setFormats(preferences.data.formats); } }, [preferences.data]);
  useEffect(() => { setConfirmArchive(false); }, [selected]);
  async function savePreferences(event: FormEvent) { event.preventDefault(); setFormatError(!formats.length); if (!formats.length) return; const result = await prefMutation.run<Preferences>('/me/preferences', { weeklyHours, formats }, 'PUT'); if (result) { preferences.refresh(); if (selected) detail.refresh(); } }
  async function createPlan(event: FormEvent) { event.preventDefault(); const target = goalValue(goal); const result = await planMutation.run<Plan>('/me/plans', { horizonDays, ...(target ? { goal: target } : {}) }, 'POST', true); if (result) { plans.refresh(); setSelected(result.id); } }
  async function updatePlan(action: 'regenerate' | 'archive') { if (!detail.data) return; const result = await detailMutation.run<Plan>(`/me/plans/${encodeURIComponent(detail.data.id)}/${action}`, { expectedVersion: detail.data.version }, 'POST', true); if (result) { plans.refresh(); detail.refresh(); setConfirmArchive(false); } }
  return <div className="growth-stack"><div className="growth-grid">
    <Panel title={c('preferences')}><QueryState query={preferences}>{() => <form className="growth-form" onSubmit={event => void savePreferences(event)}><fieldset disabled={prefMutation.busy}><Field label={c('hoursWeek')}><input type="number" min={0.5} max={40} step={0.5} required value={weeklyHours} onChange={event => setHours(Number(event.target.value))}/></Field><span>{c('formats')}</span><div className="growth-checkboxes">{(['online','offline','self_paced'] as const).map(format => <label key={format}><input type="checkbox" checked={formats.includes(format)} onChange={() => { setFormatError(false); setFormats(formats.includes(format) ? formats.filter(item => item !== format) : [...formats,format]); }}/>{c(format)}</label>)}</div>{formatError && <ErrorState message={c('chooseFormat')}/>}<p className="growth-note">{c('prefNote')}</p><Button type="submit">{prefMutation.busy ? c('busy') : c('save')}</Button></fieldset><MutationNotice mutation={prefMutation}/></form>}</QueryState></Panel>
    <Panel title={c('newPlan')}><QueryState query={profiles}>{roleProfiles => <form className="growth-form" onSubmit={event => void createPlan(event)}><fieldset disabled={planMutation.busy}><Field label={c('horizon')}><select value={horizonDays} onChange={event => setHorizon(Number(event.target.value))}>{[30,90,180].map(days => <option key={days} value={days}>{days} {c('days')}</option>)}</select></Field><Field label={c('goal')}><GoalSelect profiles={roleProfiles} value={goal} onChange={setGoal} allowCurrent/></Field><p className="growth-note">{c('planNote')}</p><Button type="submit">{planMutation.busy ? c('busy') : c('create')}</Button></fieldset><MutationNotice mutation={planMutation}/></form>}</QueryState></Panel>
  </div><Panel title={c('myPlans')} action={<Button variant="ghost" size="small" onClick={plans.refresh}>{c('refresh')}</Button>}><QueryState query={plans} empty={c('planEmpty')}>{items => <div className="growth-list">{items.map(plan => <article className="growth-item" key={plan.id}><div className="growth-row"><strong>{plan.targetRole} · {plan.targetGrade}</strong><Status value={plan.status}/></div><p>{plan.horizonDays} {c('days')} · {plan.totalHours} {c('hours')}</p><Button variant="secondary" size="small" onClick={() => setSelected(plan.id)} aria-pressed={selected === plan.id}>{c('open')}</Button></article>)}</div>}</QueryState>{(plans.data?.length ?? 0) >= 100 && <p className="growth-note">{c('latest100')}</p>}</Panel>
  {selected && <Panel title={c('steps')} action={<Button variant="ghost" size="small" onClick={() => setSelected('')}>{c('close')}</Button>}><QueryState query={detail}>{plan => <><div className="growth-row"><h3>{plan.targetRole} · {plan.targetGrade}</h3><Status value={plan.status}/></div>{plan.requiresRefresh && plan.status === 'active' && <p className="growth-note" role="status">{c('stale')}</p>}{plan.status === 'active' && <div className="growth-actions"><Button disabled={detailMutation.busy} onClick={() => void updatePlan('regenerate')}>{c('regenerate')}</Button><Button variant="secondary" disabled={detailMutation.busy} onClick={() => setConfirmArchive(true)}>{c('archive')}</Button></div>}{confirmArchive && <div className="growth-inline-confirm"><p>{c('archive')}?</p><div className="growth-actions"><Button disabled={detailMutation.busy} onClick={() => void updatePlan('archive')}>{c('confirm')}</Button><Button variant="ghost" onClick={() => setConfirmArchive(false)}>{c('cancel')}</Button></div></div>}<MutationNotice mutation={detailMutation}/><ForecastView data={plan} skills={skills.data ?? []}/></>}</QueryState></Panel>}
  </div>;
}

export function Forecasts({ session }: { session: Session }) {
  const { c } = useGrowthCopy(); const profiles = useQuery<RoleProfile[]>('/role-profiles'); const skills = useQuery<Skill[]>('/skills');
  const [goals, setGoals] = useState(['','']); const [horizonDays, setHorizon] = useState(90); const [eventIds, setEvents] = useState<string[]>([]); const [simulationGoal, setSimulationGoal] = useState('');
  const [comparisons, setComparisons] = useState<Forecast[]>(); const [forecast, setForecast] = useState<Forecast>(); const compareMutation = useMutation(session); const simulateMutation = useMutation(session);
  async function compare(event: FormEvent) { event.preventDefault(); if (goals.some(goal => !goal)) return; setComparisons(undefined); const result = await compareMutation.run<Forecast[]>('/me/growth/compare', { goals: goals.map(goalValue), horizonDays }); if (result) setComparisons(result); }
  async function simulate(event: FormEvent) { event.preventDefault(); if (!eventIds.length) return; setForecast(undefined); const goal = goalValue(simulationGoal); const result = await simulateMutation.run<Forecast>('/me/growth/simulate', { eventIds, ...(goal ? { goal } : {}) }); if (result) setForecast(result); }
  return <div className="growth-stack"><Panel title={c('compareTitle')}><p className="growth-note">{c('compareNote')}</p><QueryState query={profiles}>{roleProfiles => <form className="growth-form" onSubmit={event => void compare(event)}><fieldset disabled={compareMutation.busy}><div className="growth-grid">{goals.map((goal, index) => <div className="growth-field" key={index}><label>{c('goal')} {index + 1}<GoalSelect profiles={roleProfiles} value={goal} onChange={value => { setGoals(goals.map((item, at) => at === index ? value : item)); setComparisons(undefined); }}/></label>{goals.length > 2 && <Button size="small" variant="ghost" onClick={() => { setGoals(goals.filter((_,at) => at !== index)); setComparisons(undefined); }}>{c('remove')}</Button>}</div>)}</div><div className="growth-actions">{goals.length < 4 && <Button variant="secondary" onClick={() => setGoals([...goals,''])}>{c('addGoal')}</Button>}<Field label={c('horizon')}><select value={horizonDays} onChange={event => { setHorizon(Number(event.target.value)); setComparisons(undefined); }}>{[30,90,180].map(days => <option key={days} value={days}>{days} {c('days')}</option>)}</select></Field><Button type="submit" disabled={goals.some(goal => !goal)}>{compareMutation.busy ? c('busy') : c('compare')}</Button></div></fieldset></form>}</QueryState><MutationNotice mutation={compareMutation}/>{comparisons && <div className="growth-grid">{comparisons.map((result,index) => <article className="growth-item" key={index}><h3>{result.targetRole} · {result.targetGrade}</h3><ForecastView data={result} skills={skills.data ?? []}/></article>)}</div>}</Panel>
    <Panel title={c('simulateTitle')}><p className="growth-note">{c('simulateNote')}</p><form className="growth-form" onSubmit={event => void simulate(event)}><fieldset disabled={simulateMutation.busy}><EventPicker value={eventIds} ordered onChange={ids => { setEvents(ids); setForecast(undefined); }}/><Field label={c('goal')}><GoalSelect profiles={profiles.data ?? []} value={simulationGoal} onChange={value => { setSimulationGoal(value); setForecast(undefined); }} allowCurrent/></Field><Button type="submit" disabled={!eventIds.length}>{simulateMutation.busy ? c('busy') : c('simulate')}</Button></fieldset></form><MutationNotice mutation={simulateMutation}/>{forecast && <><p className="growth-success">{c('notPersisted')}</p><ForecastView data={forecast} skills={skills.data ?? []}/></>}</Panel>
  </div>;
}
