import { useEffect, useRef, useState, type FormEvent } from 'react';
import { api, type Session } from '../../api';
import { Button, ErrorState, Loading } from '../../components/ui';
import { statusLabel, useGrowthCopy } from './copy';
import { Field, MutationNotice, Panel, QueryState, Status, dateLabel, message, useMutation, useQuery } from './shared';
import type { Policy, Redemption, Reward, Wallet } from './types';

export function Rewards({ session }: { session: Session }) {
  const { c, locale } = useGrowthCopy(); const [synced,setSynced] = useState(false); const [syncing,setSyncing] = useState(true); const [syncError,setSyncError] = useState<unknown>(); const [syncAttempt,setSyncAttempt] = useState(0); const syncKey = useRef(crypto.randomUUID());
  const wallet = useQuery<Wallet>(synced ? '/me/rewards' : null); const catalog = useQuery<Reward[]>('/rewards/catalog'); const mutation = useMutation(session); const [selected,setSelected] = useState<Reward>();
  useEffect(() => {
    const controller = new AbortController(); setSyncing(true); setSyncError(undefined);
    void api('/me/rewards/sync',{method:'POST',body:{},csrf:session.csrfToken,idempotencyKey:syncKey.current,signal:controller.signal}).then(() => { if (!controller.signal.aborted) { syncKey.current = crypto.randomUUID(); wallet.refresh(); catalog.refresh(); } }).catch(error => { if (!controller.signal.aborted) setSyncError(error); }).finally(() => { if (!controller.signal.aborted) { setSynced(true); setSyncing(false); } });
    return () => controller.abort();
  },[session.user.id,session.csrfToken,syncAttempt]);
  async function redeem() { if (!selected) return; const result = await mutation.run('/me/rewards/redeem',{rewardId:selected.id},'POST',true); if (result) { setSelected(undefined); wallet.refresh(); catalog.refresh(); } }
  async function cancel(id: string) { const result = await mutation.run(`/me/rewards/redemptions/${encodeURIComponent(id)}`,{status:'cancelled'},'PATCH'); if (result) { wallet.refresh(); catalog.refresh(); } }
  return <div className="growth-stack"><Panel title={c('rewards')} action={<Button size="small" variant="secondary" disabled={syncing || mutation.busy} onClick={() => setSyncAttempt(value => value + 1)}>{syncing ? c('busy') : c('sync')}</Button>}><p className="growth-note">{c('rewardNote')}</p>{Boolean(syncError) && <ErrorState message={message(syncError,c)} retry={() => setSyncAttempt(value => value + 1)}/>} {syncing && !synced && <Loading/>}<QueryState query={wallet}>{data => <><div className="growth-grid"><div><span>{c('balance')}</span><div className="growth-balance">{data.balance}</div><small>{c('points')}</small></div><div><span>{c('spendable')}</span><div className="growth-balance">{data.spendableBalance}</div><small>{c('perEvent')}: {data.pointsPerEvent} · {c('monthlyCap')}: {data.monthlyCap}</small></div></div><h3>{c('rules')}</h3><p className="growth-note">{data.rules || c('rewardsOffNote')}</p>{!data.enabled && <div className="growth-success"><strong>{c('rewardsOff')}</strong><p>{c('rewardsOffNote')}</p></div>}</>}</QueryState><MutationNotice mutation={mutation}/></Panel>
    <Panel title={c('catalog')}><QueryState query={catalog}>{items => <div className="growth-grid">{items.map(reward => <article className="growth-item" key={reward.id}><h3>{reward.title}</h3><p>{reward.description}</p><p><strong>{reward.cost} {c('points')}</strong> · {c('stock')}: {reward.stock ?? c('unlimited')}</p><Button disabled={!wallet.data?.enabled || wallet.data.spendableBalance < reward.cost || reward.stock === 0 || mutation.busy || syncing} onClick={() => setSelected(reward)}>{c('redeem')}</Button>{selected?.id === reward.id && <div className="growth-inline-confirm"><p>{c('confirmRedeem')} {reward.cost} {c('points')}</p><div className="growth-actions"><Button disabled={mutation.busy} onClick={() => void redeem()}>{c('confirm')}</Button><Button variant="ghost" onClick={() => setSelected(undefined)}>{c('cancel')}</Button></div></div>}</article>)}</div>}</QueryState></Panel>
    <Panel title={c('redemptionRequests')}><QueryState query={wallet}>{data => data.redemptions.length ? <div className="growth-list">{data.redemptions.map(item => <article className="growth-item" key={item.id}><div className="growth-row"><strong>{item.title}</strong><Status value={item.status}/></div><p>{item.cost} {c('points')} · {dateLabel(item.createdAt,locale)}</p>{item.status === 'pending' && <Button variant="secondary" size="small" disabled={mutation.busy} onClick={() => void cancel(item.id)}>{c('cancel')}</Button>}</article>)}</div> : <p className="growth-note">{c('empty')}</p>}</QueryState></Panel>
    <Panel title={c('ledger')}><QueryState query={wallet}>{data => data.ledger.length ? <div className="growth-table-wrap"><table><thead><tr><th>{c('status')}</th><th>{c('points')}</th><th>{c('startsOn')}</th></tr></thead><tbody>{data.ledger.map(item => <tr key={item.id}><td>{statusLabel(c,item.kind)}{item.eventId && <small> · {item.eventId}</small>}</td><td>{item.delta > 0 ? '+' : ''}{item.delta}</td><td>{dateLabel(item.createdAt,locale)}</td></tr>)}</tbody></table></div> : <p className="growth-note">{c('empty')}</p>}</QueryState></Panel>
  </div>;
}

export function RewardsAdmin({ session }: { session: Session }) {
  const { c, locale } = useGrowthCopy(); const admin = session.user.role === 'admin'; const policy = useQuery<Policy>(admin ? '/admin/rewards/policy' : null); const catalog = useQuery<Reward[]>('/admin/rewards/catalog'); const redemptions = useQuery<Redemption[]>('/admin/rewards/redemptions');
  const [enabled,setEnabled] = useState(false); const [pointsPerEvent,setPoints] = useState(10); const [monthlyCap,setCap] = useState(100); const [rulesText,setRules] = useState('');
  const [editing,setEditing] = useState(''); const [title,setTitle] = useState(''); const [description,setDescription] = useState(''); const [cost,setCost] = useState(100); const [stock,setStock] = useState(''); const [active,setActive] = useState(true);
  const [pendingAction,setPendingAction] = useState<{id:string;status:string}>(); const policyMutation = useMutation(session); const catalogMutation = useMutation(session); const redemptionMutation = useMutation(session);
  useEffect(() => { if (policy.data) { setEnabled(policy.data.enabled); setPoints(policy.data.pointsPerEvent); setCap(policy.data.monthlyCap); setRules(policy.data.rulesText); } },[policy.data]);
  function edit(reward?: Reward) { setEditing(reward?.id ?? ''); setTitle(reward?.title ?? ''); setDescription(reward?.description ?? ''); setCost(reward?.cost ?? 100); setStock(reward?.stock == null ? '' : String(reward.stock)); setActive(reward?.active ?? true); catalogMutation.clear(); }
  async function savePolicy(event: FormEvent) { event.preventDefault(); const result = await policyMutation.run('/admin/rewards/policy',{enabled,pointsPerEvent,monthlyCap,rulesText},'PUT'); if (result) policy.refresh(); }
  async function saveReward(event: FormEvent) { event.preventDefault(); const payload = {title,description,cost,stock:stock === '' ? null : Number(stock),...(editing ? {active} : {})}; const result = await catalogMutation.run(`/admin/rewards/catalog${editing ? `/${encodeURIComponent(editing)}` : ''}`,payload,editing ? 'PATCH' : 'POST',!editing); if (result) { catalog.refresh(); edit(); } }
  async function updateRedemption() { if (!pendingAction) return; const result = await redemptionMutation.run(`/admin/rewards/redemptions/${encodeURIComponent(pendingAction.id)}`,{status:pendingAction.status},'PATCH'); if (result) { redemptions.refresh(); catalog.refresh(); setPendingAction(undefined); } }
  return <div className="growth-stack">{admin && <Panel title={c('policy')}><QueryState query={policy}>{() => <form className="growth-form" onSubmit={event => void savePolicy(event)}><fieldset disabled={policyMutation.busy}><label className="growth-check"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)}/>{c('enabled')}</label><div className="growth-grid"><Field label={c('perEvent')}><input type="number" min={1} max={1000} required value={pointsPerEvent} onChange={event => setPoints(Number(event.target.value))}/></Field><Field label={c('monthlyCap')}><input type="number" min={pointsPerEvent} max={10000} required value={monthlyCap} onChange={event => setCap(Number(event.target.value))}/></Field></div><Field label={c('rules')}><textarea required maxLength={4000} value={rulesText} onChange={event => setRules(event.target.value)}/></Field><p className="growth-note">{c('rewardNote')}</p><Button type="submit">{policyMutation.busy ? c('busy') : c('save')}</Button></fieldset><MutationNotice mutation={policyMutation}/></form>}</QueryState></Panel>}
    <Panel title={c('catalog')} action={<Button variant="ghost" size="small" onClick={catalog.refresh}>{c('refresh')}</Button>}><QueryState query={catalog}>{items => <div className="growth-grid">{items.map(reward => <article className="growth-item" key={reward.id}><div className="growth-row"><h3>{reward.title}</h3><Status value={reward.active ? 'active' : 'archived'}/></div><p>{reward.description}</p><p>{reward.cost} {c('points')} · {c('stock')}: {reward.stock ?? c('unlimited')}</p>{admin && <Button variant="secondary" size="small" onClick={() => edit(reward)}>{c('edit')}</Button>}</article>)}</div>}</QueryState></Panel>
    {admin && <Panel title={editing ? c('edit') : c('rewardTitle')}><form className="growth-form" onSubmit={event => void saveReward(event)}><fieldset disabled={catalogMutation.busy}><Field label={c('titleField')}><input required maxLength={200} value={title} onChange={event => setTitle(event.target.value)}/></Field><Field label={c('description')}><textarea required maxLength={2000} value={description} onChange={event => setDescription(event.target.value)}/></Field><div className="growth-grid"><Field label={c('cost')}><input type="number" required min={1} max={100000} value={cost} onChange={event => setCost(Number(event.target.value))}/></Field><Field label={`${c('stock')} · ${c('unlimited')}: —`}><input type="number" min={0} max={100000} value={stock} placeholder="—" onChange={event => setStock(event.target.value)}/></Field></div>{editing && <label className="growth-check"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)}/>{c('catalogActive')}</label>}<div className="growth-actions"><Button type="submit">{catalogMutation.busy ? c('busy') : c('save')}</Button>{editing && <Button variant="ghost" onClick={() => edit()}>{c('cancel')}</Button>}</div></fieldset><MutationNotice mutation={catalogMutation}/></form></Panel>}
    <Panel title={c('redemptionRequests')} action={<Button variant="ghost" size="small" onClick={redemptions.refresh}>{c('refresh')}</Button>}><MutationNotice mutation={redemptionMutation}/><QueryState query={redemptions}>{items => <div className="growth-list">{items.map(item => <article className="growth-item" key={item.id}><div className="growth-row"><strong>{item.title} · {item.fullName ?? item.employeeId}</strong><Status value={item.status}/></div><p>{item.cost} {c('points')} · {dateLabel(item.createdAt,locale)}</p>{item.status === 'pending' && <div className="growth-actions"><Button disabled={redemptionMutation.busy} size="small" onClick={() => setPendingAction({id:item.id,status:'fulfilled'})}>{c('issue')}</Button><Button disabled={redemptionMutation.busy} variant="secondary" size="small" onClick={() => setPendingAction({id:item.id,status:'cancelled'})}>{c('cancel')}</Button></div>}{pendingAction?.id === item.id && <div className="growth-inline-confirm"><p>{pendingAction.status === 'fulfilled' ? c('issue') : c('cancel')}?</p><div className="growth-actions"><Button disabled={redemptionMutation.busy} onClick={() => void updateRedemption()}>{c('confirm')}</Button><Button variant="ghost" onClick={() => setPendingAction(undefined)}>{c('close')}</Button></div></div>}</article>)}</div>}</QueryState></Panel>
  </div>;
}
