import { useEffect, useState, type FormEvent } from 'react';
import type { Session } from '../../api';
import { Button } from '../../components/ui';
import { useGrowthCopy, type CopyKey } from './copy';
import { EventPicker, Field, MutationNotice, Panel, QueryState, SkillOptions, Status, dateLabel, useMutation, useQuery } from './shared';
import type { Achievements, Challenge, Colleague, Mentor, Mentorship, Recognition, Skill, Task } from './types';

export function Mentors({ session }: { session: Session }) {
  const { c, locale } = useGrowthCopy(); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState<Mentor>(); const [requestMessage, setRequestMessage] = useState('');
  const catalog = useQuery<Mentor[]>(`/mentors${filter ? `?skillId=${encodeURIComponent(filter)}` : ''}`); const own = useQuery<Mentor | null>('/mentors/me'); const requests = useQuery<Mentorship[]>('/me/mentorships'); const skills = useQuery<Skill[]>('/skills');
  const [headline, setHeadline] = useState(''); const [skillIds, setSkills] = useState<string[]>([]); const [capacity, setCapacity] = useState(2); const [enabled, setEnabled] = useState(false);
  const profileMutation = useMutation(session); const requestMutation = useMutation(session); const statusMutation = useMutation(session);
  useEffect(() => { if (own.data) { setHeadline(own.data.headline); setSkills(own.data.skillIds); setCapacity(own.data.capacity); setEnabled(!!own.data.enabled); } }, [own.data]);
  async function saveProfile(event: FormEvent) { event.preventDefault(); if (!skillIds.length) return; const result = await profileMutation.run<Mentor>('/mentors/me', { headline, skillIds, capacity, enabled }, 'PUT'); if (result) { own.refresh(); catalog.refresh(); } }
  async function sendRequest(event: FormEvent) { event.preventDefault(); if (!selected) return; const result = await requestMutation.run('/me/mentorships', { mentorId: selected.employeeId, message: requestMessage }, 'POST', true); if (result) { requests.refresh(); catalog.refresh(); setSelected(undefined); setRequestMessage(''); } }
  async function changeStatus(id: string, status: string) { const result = await statusMutation.run(`/me/mentorships/${encodeURIComponent(id)}`, { status }, 'PATCH'); if (result) { requests.refresh(); catalog.refresh(); } }
  return <div className="growth-stack"><Panel title={c('mentorCatalog')}><Field label={c('skill')}><select value={filter} onChange={event => setFilter(event.target.value)}><option value="">{c('allSkills')}</option>{skills.data?.map(skill => <option key={skill.id} value={skill.id}>{skill.name}</option>)}</select></Field><QueryState query={catalog}>{mentors => <div className="growth-grid">{mentors.map(mentor => <article className="growth-item" key={mentor.employeeId}><h3>{mentor.fullName}</h3><p>{mentor.headline}</p><p>{mentor.skillIds.map(id => skills.data?.find(skill => skill.id === id)?.name ?? id).join(', ')}</p><p>{c('mentorCapacity')}: {Math.max(0,mentor.capacity - (mentor.activeMentees ?? 0))}</p>{mentor.employeeId !== session.user.employeeId && <Button size="small" variant="secondary" disabled={(mentor.activeMentees ?? 0) >= mentor.capacity || requests.data?.some(request => request.menteeId === session.user.employeeId && request.mentorId === mentor.employeeId && ['pending','accepted'].includes(request.status))} onClick={() => { setSelected(mentor); setRequestMessage(''); requestMutation.clear(); }}>{c('requestMentor')}</Button>}</article>)}</div>}</QueryState>{selected && <form className="growth-form growth-inline-confirm" onSubmit={event => void sendRequest(event)}><h3>{selected.fullName}</h3><fieldset disabled={requestMutation.busy}><Field label={c('message')}><textarea value={requestMessage} required maxLength={2000} placeholder={c('mentorMessage')} onChange={event => setRequestMessage(event.target.value)}/></Field><div className="growth-actions"><Button type="submit">{requestMutation.busy ? c('busy') : c('send')}</Button><Button variant="ghost" onClick={() => setSelected(undefined)}>{c('cancel')}</Button></div></fieldset></form>}<MutationNotice mutation={requestMutation}/></Panel>
    <Panel title={c('requests')} action={<Button variant="ghost" size="small" onClick={requests.refresh}>{c('refresh')}</Button>}><MutationNotice mutation={statusMutation}/><QueryState query={requests}>{items => <div className="growth-list">{items.map(request => <article className="growth-item" key={request.id}><div className="growth-row"><strong>{request.mentorId === session.user.employeeId ? `${c('mentee')}: ${request.menteeName}` : `${c('mentor')}: ${request.mentorName}`}</strong><Status value={request.status}/></div><p>{request.message}</p><small>{dateLabel(request.createdAt,locale)}</small><div className="growth-actions">{request.status === 'pending' && request.mentorId === session.user.employeeId && <><Button disabled={statusMutation.busy} onClick={() => void changeStatus(request.id,'accepted')}>{c('accept')}</Button><Button disabled={statusMutation.busy} variant="secondary" onClick={() => void changeStatus(request.id,'declined')}>{c('decline')}</Button></>}{request.status === 'accepted' && <Button disabled={statusMutation.busy} onClick={() => void changeStatus(request.id,'completed')}>{c('complete')}</Button>}{['accepted','pending'].includes(request.status) && <Button disabled={statusMutation.busy} variant="ghost" onClick={() => void changeStatus(request.id,'cancelled')}>{c('cancel')}</Button>}</div></article>)}</div>}</QueryState></Panel>
    <Panel title={c('myMentor')}><p className="growth-note">{c('mentorNote')}</p><QueryState query={own}>{profile => <><p>{profile?.enabled ? profile.approvedAt ? c('approved') : c('awaitingApproval') : c('publishConsent')}</p><form className="growth-form" onSubmit={event => void saveProfile(event)}><fieldset disabled={profileMutation.busy}><Field label={c('headline')}><textarea required maxLength={300} value={headline} onChange={event => setHeadline(event.target.value)}/></Field><QueryState query={skills}>{items => <SkillOptions skills={items} selected={skillIds} onChange={setSkills}/>}</QueryState><Field label={c('capacity')}><input type="number" min={1} max={20} required value={capacity} onChange={event => setCapacity(Number(event.target.value))}/></Field><label className="growth-check"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)}/>{c('publishConsent')}</label><Button type="submit" disabled={!skillIds.length}>{profileMutation.busy ? c('busy') : c('save')}</Button></fieldset><MutationNotice mutation={profileMutation}/></form></>}</QueryState></Panel>
  </div>;
}

export function Tasks({ session }: { session: Session }) {
  const { c, locale } = useGrowthCopy(); const tasks = useQuery<Task[]>('/me/tasks'); const achievements = useQuery<Achievements>('/me/achievements'); const skills = useQuery<Skill[]>('/skills');
  const [title,setTitle] = useState(''); const [skill,setSkill] = useState(''); const [level,setLevel] = useState(1); const [dueDate,setDueDate] = useState(''); const mutation = useMutation(session);
  async function create(event: FormEvent) { event.preventDefault(); const result = await mutation.run('/me/tasks', { title, ...(skill ? { skillId: skill, targetLevel: level } : {}), ...(dueDate ? { dueDate } : {}) }, 'POST', true); if (result) { tasks.refresh(); setTitle(''); setSkill(''); setDueDate(''); } }
  async function update(id: string, status: string) { const result = await mutation.run(`/me/tasks/${encodeURIComponent(id)}`, { status }, 'PATCH'); if (result) { tasks.refresh(); achievements.refresh(); } }
  return <div className="growth-stack"><div className="growth-grid"><Panel title={c('personalTask')}><p className="growth-note">{c('taskNote')}</p><form className="growth-form" onSubmit={event => void create(event)}><fieldset disabled={mutation.busy}><Field label={c('titleField')}><input required maxLength={200} value={title} onChange={event => setTitle(event.target.value)}/></Field><Field label={`${c('skill')} · ${c('optional')}`}><select value={skill} onChange={event => setSkill(event.target.value)}><option value="">—</option>{skills.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>{skill && <Field label={c('targetLevel')}><select value={level} onChange={event => setLevel(Number(event.target.value))}>{[1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select></Field>}<Field label={`${c('dueDate')} · ${c('optional')}`}><input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)}/></Field><Button type="submit">{mutation.busy ? c('busy') : c('create')}</Button></fieldset></form><MutationNotice mutation={mutation}/></Panel>
    <Panel title={c('achievements')}><p className="growth-note">{c('achievementNote')}</p><QueryState query={achievements}>{data => <div className="growth-list">{data.achievements.map(item => <article className="growth-item growth-achievement" key={item.id}><strong>{['first_learning','five_activities','ten_activities'].includes(item.id) ? c(item.id as CopyKey) : item.title}</strong><progress max={item.target} value={item.current} aria-label={['first_learning','five_activities','ten_activities'].includes(item.id) ? c(item.id as CopyKey) : item.title}/><span>{item.current}/{item.target} {item.achieved && '✓'}</span></article>)}{data.goalReady && <p className="growth-success">{c('goalReady')}</p>}</div>}</QueryState></Panel></div>
    <Panel title={c('tasks')} action={<Button variant="ghost" size="small" onClick={tasks.refresh}>{c('refresh')}</Button>}><QueryState query={tasks}>{items => <div className="growth-list">{items.map(task => <article className="growth-item" key={task.id}><div className="growth-row"><strong>{task.title}</strong><Status value={task.status}/></div>{task.skillId && <p>{skills.data?.find(item => item.id === task.skillId)?.name ?? task.skillId}: {task.targetLevel}/5</p>}{task.dueDate && <p>{c('dueDate')}: {dateLabel(task.dueDate,locale)}</p>}{task.status === 'active' && <div className="growth-actions"><Button disabled={mutation.busy} size="small" onClick={() => void update(task.id,'completed')}>{c('complete')}</Button><Button disabled={mutation.busy} size="small" variant="ghost" onClick={() => void update(task.id,'cancelled')}>{c('cancel')}</Button></div>}</article>)}</div>}</QueryState></Panel>
  </div>;
}

export function Thanks({ session }: { session: Session }) {
  const { c, locale } = useGrowthCopy(); const list = useQuery<Recognition[]>('/me/recognitions'); const [search,setSearch] = useState(''); const [query,setQuery] = useState(''); const [recipient,setRecipient] = useState<Colleague>(); const [message,setMessage] = useState(''); const [report,setReport] = useState(''); const mutation = useMutation(session);
  useEffect(() => { const timer = setTimeout(() => setQuery(search.trim()),300); return () => clearTimeout(timer); },[search]);
  const colleagues = useQuery<Colleague[]>(query.length >= 2 ? `/colleagues?q=${encodeURIComponent(query)}` : null);
  async function send(event: FormEvent) { event.preventDefault(); if (!recipient) return; const result = await mutation.run('/me/recognitions', { recipientId: recipient.employeeId, message }, 'POST', true); if (result) { list.refresh(); setMessage(''); setRecipient(undefined); setSearch(''); } }
  async function update(id: string, status: string) { const result = await mutation.run(`/me/recognitions/${encodeURIComponent(id)}`, { status }, 'PATCH'); if (result) { setReport(''); list.refresh(); } }
  return <div className="growth-stack"><Panel title={c('thankTitle')}><p className="growth-note">{c('thankNote')}</p><form className="growth-form" onSubmit={event => void send(event)}><fieldset disabled={mutation.busy}><Field label={c('colleagueSearch')}><input type="search" maxLength={80} value={search} onChange={event => { setSearch(event.target.value); setRecipient(undefined); }}/></Field>{query.length >= 2 && !recipient && <QueryState query={colleagues}>{items => <div className="growth-list">{items.filter(item => item.employeeId !== session.user.employeeId).map(item => <Button key={item.employeeId} variant="secondary" onClick={() => setRecipient(item)}>{item.fullName} · {item.department}</Button>)}</div>}</QueryState>}{recipient && <p className="growth-success">{c('recipient')}: {recipient.fullName}</p>}<Field label={c('message')}><textarea required maxLength={1000} value={message} onChange={event => setMessage(event.target.value)}/></Field><Button type="submit" disabled={!recipient}>{mutation.busy ? c('busy') : c('send')}</Button></fieldset></form><MutationNotice mutation={mutation}/></Panel>
    <Panel title={c('thanks')} action={<Button size="small" variant="ghost" onClick={list.refresh}>{c('refresh')}</Button>}><QueryState query={list}>{items => <div className="growth-list">{items.map(item => <article key={item.id} className="growth-item"><div className="growth-row"><strong>{item.senderId === session.user.employeeId ? `${c('sent')}: ${item.recipientName}` : `${c('received')}: ${item.senderName}`}</strong><Status value={item.status}/></div><p>{item.message}</p><small>{dateLabel(item.createdAt,locale)}</small>{item.recipientId === session.user.employeeId && ['pending','accepted'].includes(item.status) && <div className="growth-actions">{item.status === 'pending' && <><Button disabled={mutation.busy} size="small" onClick={() => void update(item.id,'accepted')}>{c('accept')}</Button><Button disabled={mutation.busy} size="small" variant="secondary" onClick={() => void update(item.id,'declined')}>{c('decline')}</Button></>}<Button disabled={mutation.busy} size="small" variant="ghost" onClick={() => setReport(item.id)}>{c('report')}</Button></div>}{report === item.id && <div className="growth-inline-confirm"><p>{c('reportNote')}</p><div className="growth-actions"><Button disabled={mutation.busy} onClick={() => void update(item.id,'reported')}>{c('confirm')}</Button><Button variant="ghost" onClick={() => setReport('')}>{c('cancel')}</Button></div></div>}</article>)}</div>}</QueryState></Panel>
  </div>;
}

export function Teams({ session }: { session: Session }) {
  const { c, locale } = useGrowthCopy(); const list = useQuery<Challenge[]>(session.user.employeeId ? '/team-challenges' : null); const mutation = useMutation(session);
  const [title,setTitle] = useState(''); const [description,setDescription] = useState(''); const [startsOn,setStart] = useState(''); const [endsOn,setEnd] = useState(''); const [eventIds,setEvents] = useState<string[]>([]); const [created,setCreated] = useState<{id:string;title:string}[]>([]); const [archive,setArchive] = useState('');
  const canCreate = ['manager','hr','admin'].includes(session.user.role);
  async function create(event: FormEvent) { event.preventDefault(); if (!eventIds.length) return; const result = await mutation.run<{id:string}>('/team-challenges', { title,description,startsOn,endsOn,eventIds }, 'POST', true); if (result) { setCreated(items => [...items,{id:result.id,title}]); list.refresh(); setTitle(''); setDescription(''); setEvents([]); } }
  async function action(id: string, action: string) { const result = await mutation.run(`/team-challenges/${encodeURIComponent(id)}/${action}`); if (result) { list.refresh(); setArchive(''); if (action === 'archive') setCreated(items => items.filter(item => item.id !== id)); } }
  return <div className="growth-stack"><Panel title={c('teamTitle')} action={session.user.employeeId && <Button size="small" variant="ghost" onClick={list.refresh}>{c('refresh')}</Button>}><p className="growth-note">{c('teamNote')}</p><MutationNotice mutation={mutation}/>{session.user.employeeId ? <QueryState query={list}>{items => <div className="growth-list">{items.map(item => <article className="growth-item" key={item.id}><div className="growth-row"><h3>{item.title}</h3><Status value={item.status}/></div><p>{item.description}</p><p>{dateLabel(item.startsOn,locale)} — {dateLabel(item.endsOn,locale)}</p><p>{c('members')}: {item.memberCount} · {c('completedMembers')}: {item.completedMembers}</p><ul>{item.events.map(event => <li key={event.eventId}>{event.completed && '✓ '}{event.title}</li>)}</ul><div className="growth-actions">{item.joined ? <Button disabled={mutation.busy} variant="secondary" onClick={() => void action(item.id,'leave')}>{c('leave')}</Button> : item.status === 'active' && <Button disabled={mutation.busy} onClick={() => void action(item.id,'join')}>{c('join')}</Button>}{item.status === 'active' && (['hr','admin'].includes(session.user.role) || item.canArchive || item.createdBy === session.user.id || created.some(local => local.id === item.id)) && <Button disabled={mutation.busy} variant="ghost" onClick={() => setArchive(item.id)}>{c('archive')}</Button>}</div>{archive === item.id && <div className="growth-inline-confirm"><div className="growth-actions"><Button disabled={mutation.busy} onClick={() => void action(item.id,'archive')}>{c('confirm')}</Button><Button variant="ghost" onClick={() => setArchive('')}>{c('cancel')}</Button></div></div>}</article>)}</div>}</QueryState> : <p className="growth-note">{c('listEmployee')}</p>}{!session.user.employeeId && created.map(item => <article key={item.id} className="growth-item"><strong>{item.title}</strong><p>{c('teamCreated')}</p><Button variant="secondary" disabled={mutation.busy} onClick={() => setArchive(item.id)}>{c('archive')}</Button>{archive === item.id && <div className="growth-actions"><Button disabled={mutation.busy} onClick={() => void action(item.id,'archive')}>{c('confirm')}</Button><Button variant="ghost" onClick={() => setArchive('')}>{c('cancel')}</Button></div>}</article>)}</Panel>
    {canCreate && <Panel title={c('createTeam')}><form className="growth-form" onSubmit={event => void create(event)}><fieldset disabled={mutation.busy}><Field label={c('titleField')}><input required maxLength={200} value={title} onChange={event => setTitle(event.target.value)}/></Field><Field label={c('description')}><textarea required maxLength={2000} value={description} onChange={event => setDescription(event.target.value)}/></Field><div className="growth-grid"><Field label={c('startsOn')}><input required type="date" value={startsOn} onChange={event => setStart(event.target.value)}/></Field><Field label={c('endsOn')}><input required type="date" min={startsOn} value={endsOn} onChange={event => setEnd(event.target.value)}/></Field></div><EventPicker value={eventIds} onChange={setEvents} max={10}/><Button type="submit" disabled={!eventIds.length}>{mutation.busy ? c('busy') : c('create')}</Button></fieldset></form></Panel>}
  </div>;
}
