const en = {
  people: 'People', team: 'My team', own: 'My profile',
  peopleSub: 'Meet the people in your organization and explore their profiles.',
  teamSub: 'Your profile and the people who report directly to you.',
  ownSub: 'Your role, work details and current career goal in one place.',
  profiles: 'Accessible profiles', search: 'Search by name, role or department',
  clear: 'Clear search', employee: 'Employee', position: 'Role and grade', department: 'Department',
  open: 'View profile', you: 'You', noResults: 'No matching profiles',
  noResultsSub: 'Try another name, role or department.', noPeople: 'No profiles yet',
  noPeopleSub: 'Profiles will appear here after employee data is imported.',
  previous: 'Previous', next: 'Next', page: 'Page', of: 'of', shown: 'Shown',
  loadError: 'Profiles could not be loaded. Check your connection and try again.',
  profileError: 'This profile could not be loaded. Please try again.',
  profileTitle: 'Employee profile', profileSub: 'Current work details and career goal.',
  back: 'Back to people', workspace: 'Back to workspace', goal: 'Career goal',
  goalSub: 'The next role or grade recorded in the employee profile.',
  targetRole: 'Target role', targetGrade: 'Target grade', noGoal: 'No career goal recorded',
  noGoalSub: 'A career goal will appear here when it is added to the employee data.',
  details: 'Work details', detailsSub: 'Information from the current employee dataset.',
  hireDate: 'Start date', tenure: 'Time at company', months: 'months',
  workFormat: 'Work format', review: 'Last assessment', language: 'Preferred language',
  manager: 'Manager ID', employeeId: 'Employee ID', notSet: 'Not specified',
  office: 'Office', hybrid: 'Hybrid', remote: 'Remote',
  russian: 'Russian', kazakh: 'Kazakh', english: 'English',
  inaccessible: 'Profile unavailable',
  inaccessibleSub: 'This profile does not exist or is outside your access scope.',
  noLinked: 'Your profile has not been linked yet',
  noLinkedSub: 'Ask an administrator to link your account to an employee profile.',
  accessNote: 'You can view the profiles available to your role.',
};

type Copy = typeof en;
const ru: Copy = {
  people: 'Сотрудники', team: 'Моя команда', own: 'Мой профиль',
  peopleSub: 'Знакомьтесь с сотрудниками организации и изучайте их профили.',
  teamSub: 'Ваш профиль и сотрудники в вашем прямом подчинении.',
  ownSub: 'Должность, информация о работе и карьерная цель в одном месте.',
  profiles: 'Доступные профили', search: 'Поиск по имени, должности или отделу',
  clear: 'Сбросить поиск', employee: 'Сотрудник', position: 'Должность и грейд', department: 'Отдел',
  open: 'Открыть профиль', you: 'Вы', noResults: 'Профили не найдены',
  noResultsSub: 'Попробуйте другое имя, должность или отдел.', noPeople: 'Пока нет профилей',
  noPeopleSub: 'Профили появятся после загрузки данных сотрудников.',
  previous: 'Назад', next: 'Далее', page: 'Страница', of: 'из', shown: 'Показано',
  loadError: 'Не удалось загрузить сотрудников. Проверьте подключение и повторите попытку.',
  profileError: 'Не удалось загрузить профиль. Попробуйте ещё раз.',
  profileTitle: 'Профиль сотрудника', profileSub: 'Текущие данные о работе и карьерная цель.',
  back: 'К сотрудникам', workspace: 'В рабочее пространство', goal: 'Карьерная цель',
  goalSub: 'Следующая должность или грейд, указанные в профиле сотрудника.',
  targetRole: 'Целевая должность', targetGrade: 'Целевой грейд', noGoal: 'Карьерная цель не указана',
  noGoalSub: 'Цель появится здесь после её добавления в данные сотрудника.',
  details: 'О работе', detailsSub: 'Информация из текущего набора данных сотрудников.',
  hireDate: 'Дата приёма', tenure: 'Стаж в компании', months: 'мес.',
  workFormat: 'Формат работы', review: 'Последняя оценка', language: 'Предпочитаемый язык',
  manager: 'ID руководителя', employeeId: 'ID сотрудника', notSet: 'Не указано',
  office: 'Офис', hybrid: 'Гибрид', remote: 'Удалённо',
  russian: 'Русский', kazakh: 'Казахский', english: 'Английский',
  inaccessible: 'Профиль недоступен',
  inaccessibleSub: 'Такого профиля нет или он находится вне вашей области доступа.',
  noLinked: 'Ваш профиль ещё не привязан',
  noLinkedSub: 'Попросите администратора связать ваш аккаунт с профилем сотрудника.',
  accessNote: 'В списке показаны профили, доступные вашей роли.',
};

const kk: Copy = {
  people: 'Қызметкерлер', team: 'Менің командам', own: 'Менің профилім',
  peopleSub: 'Ұйым қызметкерлерімен және олардың профильдерімен танысыңыз.',
  teamSub: 'Сіздің және тікелей бағынышты қызметкерлердің профильдері.',
  ownSub: 'Лауазым, жұмыс туралы мәліметтер және мансаптық мақсат бір жерде.',
  profiles: 'Қолжетімді профильдер', search: 'Аты, лауазымы немесе бөлімі бойынша іздеу',
  clear: 'Іздеуді тазалау', employee: 'Қызметкер', position: 'Лауазым және деңгей', department: 'Бөлім',
  open: 'Профильді ашу', you: 'Сіз', noResults: 'Профильдер табылмады',
  noResultsSub: 'Басқа атты, лауазымды немесе бөлімді іздеп көріңіз.', noPeople: 'Профильдер әзірге жоқ',
  noPeopleSub: 'Қызметкерлер деректері жүктелгеннен кейін профильдер пайда болады.',
  previous: 'Артқа', next: 'Алға', page: 'Бет', of: '/', shown: 'Көрсетілгені',
  loadError: 'Қызметкерлер жүктелмеді. Байланысты тексеріп, әрекетті қайталаңыз.',
  profileError: 'Профиль жүктелмеді. Қайталап көріңіз.',
  profileTitle: 'Қызметкер профилі', profileSub: 'Жұмыс туралы қазіргі мәліметтер және мансаптық мақсат.',
  back: 'Қызметкерлерге оралу', workspace: 'Жұмыс кеңістігіне оралу', goal: 'Мансаптық мақсат',
  goalSub: 'Қызметкер профилінде көрсетілген келесі лауазым немесе деңгей.',
  targetRole: 'Мақсатты лауазым', targetGrade: 'Мақсатты деңгей', noGoal: 'Мансаптық мақсат көрсетілмеген',
  noGoalSub: 'Мақсат қызметкер деректеріне қосылғаннан кейін осы жерде пайда болады.',
  details: 'Жұмыс туралы', detailsSub: 'Қызметкерлердің қазіргі деректер жинағындағы мәліметтер.',
  hireDate: 'Жұмысқа кірген күн', tenure: 'Компаниядағы еңбек өтілі', months: 'ай',
  workFormat: 'Жұмыс форматы', review: 'Соңғы бағалау', language: 'Қалаулы тіл',
  manager: 'Басшының ID нөмірі', employeeId: 'Қызметкердің ID нөмірі', notSet: 'Көрсетілмеген',
  office: 'Кеңседе', hybrid: 'Аралас', remote: 'Қашықтан',
  russian: 'Орысша', kazakh: 'Қазақша', english: 'Ағылшынша',
  inaccessible: 'Профиль қолжетімсіз',
  inaccessibleSub: 'Бұл профиль жоқ немесе оған қол жеткізу құқығыңыз жоқ.',
  noLinked: 'Профиліңіз әлі байланыстырылмаған',
  noLinkedSub: 'Әкімшіден аккаунтыңызды қызметкер профилімен байланыстыруды сұраңыз.',
  accessNote: 'Тізімде рөліңізге қолжетімді профильдер көрсетілген.',
};

export const peopleCopy = { ru, kk, en };
export const dateLocales = { ru: 'ru-RU', kk: 'kk-KZ', en: 'en-GB' };
