#!/usr/bin/env python3
"""Prepare a restricted SSH tunnel and ignored config; never print credentials.

Requires an already running model (serve.sh) and an authenticated Brev SSH alias.
Run again after Brev stop/start if its gateway port or host key changes.
"""
import argparse
import os
from pathlib import Path
import re
import subprocess


def run(args, *, data=None):
    return subprocess.run(args, input=data, text=True, check=True,
                          stdout=subprocess.PIPE).stdout.strip()


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--instance", default="career-quest-ai")
args = parser.parse_args()
if not re.fullmatch(r"[a-zA-Z0-9][a-zA-Z0-9_.-]*", args.instance):
    parser.error("Invalid SSH alias")
root = Path(__file__).resolve().parents[2]
os.umask(0o077)
cache = root / ".cache/brev"
cache.mkdir(parents=True, exist_ok=True)
env_path = root / ".env.brev"
marker = "# Generated by infra/brev/connect.py; contains local secrets."
if env_path.exists() and not env_path.read_text().startswith(marker):
    raise SystemExit(".env.brev exists and was not generated by this script; preserve it manually.")
config = {}
for line in run(["ssh", "-G", args.instance]).splitlines():
    key, _, value = line.partition(" ")
    config.setdefault(key, value)
host, port, user = (config[k] for k in ("hostname", "port", "user"))
if not re.fullmatch(r"[a-zA-Z0-9.-]+", host) or not port.isdigit() or not re.fullmatch(r"[a-zA-Z0-9_-]+", user):
    raise SystemExit("Unsupported SSH gateway configuration")
if config.get("proxycommand", "none") != "none" or config.get("proxyjump", "none") != "none":
    raise SystemExit("This tunnel expects a direct Brev SSH gateway; proxy configuration requires review.")
ssh = ["ssh", "-T", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", args.instance]
private_key = cache / "id_ed25519"
if not private_key.exists():
    run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C", "career-quest-model-tunnel", "-f", str(private_key)])
public_key = private_key.with_suffix(".pub").read_text().strip()
if not re.fullmatch(r"ssh-ed25519 [A-Za-z0-9+/=]+ career-quest-model-tunnel", public_key):
    raise SystemExit("Unexpected tunnel public key")
restricted = 'restrict,port-forwarding,permitopen="127.0.0.1:8000",command="/bin/false" ' + public_key
remote_script = """import os, pathlib
os.umask(0o077)
directory=pathlib.Path.home()/'.ssh'
directory.mkdir(exist_ok=True, mode=0o700)
path=directory/'authorized_keys'
line=RESTRICTED_LINE
existing=path.read_text() if path.exists() else ''
if line not in existing.splitlines():
    with path.open('a') as f:
        f.write(('\\n' if existing and not existing.endswith('\\n') else '')+line+'\\n')
os.chmod(path,0o600)
""".replace("RESTRICTED_LINE", repr(restricted))
run(ssh + ["python3 -"], data=remote_script)
# The public host key is read through the authenticated Brev connection.
host_key = run(ssh + ["cat /etc/ssh/ssh_host_ed25519_key.pub"]).split()
if len(host_key) < 2 or host_key[0] != "ssh-ed25519":
    raise SystemExit("Unexpected remote host key")
known_host = host if port == "22" else f"[{host}]:{port}"
(cache / "known_hosts").write_text(f"{known_host} {host_key[0]} {host_key[1]}\n")
runtime = run(ssh + ["cat ~/career-quest-ai/runtime.env"])
values = dict(line.split("=", 1) for line in runtime.splitlines() if "=" in line)
token = values.get("VLLM_API_KEY", "")
if not re.fullmatch(r"[A-Za-z0-9_-]{40,128}", token):
    raise SystemExit("Model API credential absent or invalid; run serve.sh first")
settings = {
    "AI_ENABLED": "true",
    "AI_PROVIDER": "self_hosted",
    "AI_BASE_URL": "http://127.0.0.1:18000/v1",
    "AI_API_KEY": token,
    "AI_MODEL_FAST": "Qwen/Qwen3-4B-Instruct-2507",
    "AI_MODEL_RECOMMEND": "Qwen/Qwen3-4B-Instruct-2507",
    "AI_TIMEOUT_MS": "20000",
    "AI_MAX_CONCURRENT_REQUESTS": "2",
    "AI_INPUT_USD_PER_MILLION": "0",
    "AI_OUTPUT_USD_PER_MILLION": "0",
    "AI_EMBEDDING_ENABLED": "false",
    "OPENAI_API_KEY": "",
    "BREV_SSH_HOST": host,
    "BREV_SSH_PORT": port,
    "BREV_SSH_USER": user,
}
temporary = env_path.with_name(".env.brev.tmp")
temporary.write_text(marker + "\n" + "\n".join(f"{k}={v}" for k, v in settings.items()) + "\n")
temporary.chmod(0o600)
temporary.replace(env_path)
print("Prepared .env.brev and restricted .cache/brev SSH credentials (ignored by Git).")
print("Start: python3 infra/brev/compose.py up -d --build --wait")
